CREATE OR REPLACE PACKAGE BODY FIDE_TAREA3_PCK AS

PROCEDURE FIDE_CLIENTES_INSERT_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_REGISTRO IN TAREA1.FIDE_CLIENTES_TB.FECHA_REGISTRO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_CLIENTES_TB(
ID_CLIENTE,
NOMBRE,
APELLIDO_PATERNO,
APELLIDO_MATERNO,
FECHA_REGISTRO,
ID_CORREO,
ID_DIRECCION,
ID_ESTADO
)
VALUES(
P_ID_CLIENTE,
P_NOMBRE,
P_APELLIDO_PATERNO,
P_APELLIDO_MATERNO,
P_FECHA_REGISTRO,
P_ID_CORREO,
P_ID_DIRECCION,
P_ID_ESTADO
);
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error insertando cliente: ' || SQLERRM);
RAISE;
END FIDE_CLIENTES_INSERT_SP;

PROCEDURE FIDE_CLIENTES_UPDATE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CLIENTES_TB
SET NOMBRE = P_NOMBRE,
APELLIDO_PATERNO = P_APELLIDO_PATERNO,
APELLIDO_MATERNO = P_APELLIDO_MATERNO,
ID_CORREO = P_ID_CORREO,
ID_DIRECCION = P_ID_DIRECCION
WHERE ID_CLIENTE = P_ID_CLIENTE;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el cliente indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error actualizando cliente: ' || SQLERRM);
RAISE;
END FIDE_CLIENTES_UPDATE_SP;

PROCEDURE FIDE_CLIENTES_DELETE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CLIENTES_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_CLIENTE = P_ID_CLIENTE;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el cliente indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error eliminando cliente: ' || SQLERRM);
RAISE;
END FIDE_CLIENTES_DELETE_SP;

PROCEDURE FIDE_MASCOTAS_INSERT_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_MASCOTAS_TB(
ID_MASCOTA,
ID_CLIENTE,
ID_RAZA,
NOMBRE,
EDAD,
PESO,
OBSERVACIONES,
ID_ESTADO
)
VALUES(
P_ID_MASCOTA,
P_ID_CLIENTE,
P_ID_RAZA,
P_NOMBRE,
P_EDAD,
P_PESO,
P_OBSERVACIONES,
P_ID_ESTADO
);
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error insertando mascota: ' || SQLERRM);
RAISE;
END FIDE_MASCOTAS_INSERT_SP;

PROCEDURE FIDE_MASCOTAS_UPDATE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_MASCOTAS_TB
SET ID_CLIENTE = P_ID_CLIENTE,
ID_RAZA = P_ID_RAZA,
NOMBRE = P_NOMBRE,
EDAD = P_EDAD,
PESO = P_PESO,
OBSERVACIONES = P_OBSERVACIONES
WHERE ID_MASCOTA = P_ID_MASCOTA;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe la mascota indicada');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error actualizando mascota: ' || SQLERRM);
RAISE;
END FIDE_MASCOTAS_UPDATE_SP;

PROCEDURE FIDE_MASCOTAS_DELETE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_MASCOTAS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_MASCOTA = P_ID_MASCOTA;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe la mascota indicada');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error eliminando mascota: ' || SQLERRM);
RAISE;
END FIDE_MASCOTAS_DELETE_SP;

PROCEDURE FIDE_CITAS_INSERT_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_CITAS_TB(
ID_CITA,
ID_MASCOTA,
FECHA_HORA,
NOTAS_GROOMER,
ID_ESTADO
)
VALUES(
P_ID_CITA,
P_ID_MASCOTA,
P_FECHA_HORA,
P_NOTAS_GROOMER,
P_ID_ESTADO
);
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error insertando cita: ' || SQLERRM);
RAISE;
END FIDE_CITAS_INSERT_SP;

PROCEDURE FIDE_CITAS_UPDATE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CITAS_TB
SET ID_MASCOTA = P_ID_MASCOTA,
FECHA_HORA = P_FECHA_HORA,
NOTAS_GROOMER = P_NOTAS_GROOMER
WHERE ID_CITA = P_ID_CITA;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe la cita indicada');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error actualizando cita: ' || SQLERRM);
RAISE;
END FIDE_CITAS_UPDATE_SP;

PROCEDURE FIDE_CITAS_DELETE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CITAS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_CITA = P_ID_CITA;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe la cita indicada');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error eliminando cita: ' || SQLERRM);
RAISE;
END FIDE_CITAS_DELETE_SP;

PROCEDURE FIDE_SERVICIOS_INSERT_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_SERVICIOS_TB(
ID_SERVICIO,
NOMBRE,
DESCRIPCION,
PRECIO_ESTANDAR,
DURACION,
ID_ESTADO
)
VALUES(
P_ID_SERVICIO,
P_NOMBRE,
P_DESCRIPCION,
P_PRECIO_ESTANDAR,
P_DURACION,
P_ID_ESTADO
);
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('El servicio ya existe');
RAISE;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error insertando servicio: ' || SQLERRM);
RAISE;
END FIDE_SERVICIOS_INSERT_SP;

PROCEDURE FIDE_SERVICIOS_UPDATE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_SERVICIOS_TB
SET NOMBRE = P_NOMBRE,
DESCRIPCION = P_DESCRIPCION,
PRECIO_ESTANDAR = P_PRECIO_ESTANDAR,
DURACION = P_DURACION
WHERE ID_SERVICIO = P_ID_SERVICIO;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el servicio indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error actualizando servicio: ' || SQLERRM);
RAISE;
END FIDE_SERVICIOS_UPDATE_SP;

PROCEDURE FIDE_SERVICIOS_DELETE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_SERVICIOS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_SERVICIO = P_ID_SERVICIO;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el servicio indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error eliminando servicio: ' || SQLERRM);
RAISE;
END FIDE_SERVICIOS_DELETE_SP;

PROCEDURE FIDE_PAGOS_INSERT_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_CITA IN TAREA1.FIDE_PAGOS_TB.ID_CITA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_PAGOS_TB.ID_CLIENTE%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_PAGOS_TB(
ID_PAGO,
ID_CITA,
ID_CLIENTE,
FECHA_PAGO,
MONTO_TOTAL,
METODO_PAGO,
ID_ESTADO
)
VALUES(
P_ID_PAGO,
P_ID_CITA,
P_ID_CLIENTE,
P_FECHA_PAGO,
P_MONTO_TOTAL,
P_METODO_PAGO,
P_ID_ESTADO
);
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error insertando pago: ' || SQLERRM);
RAISE;
END FIDE_PAGOS_INSERT_SP;

PROCEDURE FIDE_PAGOS_UPDATE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PAGOS_TB
SET FECHA_PAGO = P_FECHA_PAGO,
MONTO_TOTAL = P_MONTO_TOTAL,
METODO_PAGO = P_METODO_PAGO
WHERE ID_PAGO = P_ID_PAGO;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el pago indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error actualizando pago: ' || SQLERRM);
RAISE;
END FIDE_PAGOS_UPDATE_SP;

PROCEDURE FIDE_PAGOS_DELETE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PAGOS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_PAGO = P_ID_PAGO;

IF SQL%ROWCOUNT = 0 THEN
DBMS_OUTPUT.PUT_LINE('No existe el pago indicado');
END IF;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error eliminando pago: ' || SQLERRM);
RAISE;
END FIDE_PAGOS_DELETE_SP;

FUNCTION FIDE_FN_MASCOTAS_POR_CLIENTE(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
) RETURN NUMBER IS
CURSOR C_MASCOTAS IS
SELECT COUNT(*)
FROM TAREA1.FIDE_MASCOTAS_TB
WHERE ID_CLIENTE = P_ID_CLIENTE;
V_CANTIDAD NUMBER := 0;
BEGIN
OPEN C_MASCOTAS;
FETCH C_MASCOTAS INTO V_CANTIDAD;
CLOSE C_MASCOTAS;
RETURN NVL(V_CANTIDAD,0);
EXCEPTION
WHEN OTHERS THEN
IF C_MASCOTAS%ISOPEN THEN
CLOSE C_MASCOTAS;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_MASCOTAS_POR_CLIENTE: ' || SQLERRM);
RETURN 0;
END FIDE_FN_MASCOTAS_POR_CLIENTE;

FUNCTION FIDE_FN_ULTIMA_CITA_MASCOTA(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE
) RETURN DATE IS
CURSOR C_ULTIMA_CITA IS
SELECT MAX(FECHA_HORA)
FROM TAREA1.FIDE_CITAS_TB
WHERE ID_MASCOTA = P_ID_MASCOTA;
V_FECHA DATE;
BEGIN
OPEN C_ULTIMA_CITA;
FETCH C_ULTIMA_CITA INTO V_FECHA;
CLOSE C_ULTIMA_CITA;
RETURN V_FECHA;
EXCEPTION
WHEN OTHERS THEN
IF C_ULTIMA_CITA%ISOPEN THEN
CLOSE C_ULTIMA_CITA;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_ULTIMA_CITA_MASCOTA: ' || SQLERRM);
RETURN NULL;
END FIDE_FN_ULTIMA_CITA_MASCOTA;

FUNCTION FIDE_FN_ESTADO_FACTURA(
P_ID_FACTURA IN TAREA1.FIDE_FACTURAS_TB.ID_FACTURA%TYPE
) RETURN VARCHAR2 IS
CURSOR C_ESTADO_FACTURA IS
SELECT E.NOMBRE_ESTADO
FROM TAREA1.FIDE_FACTURAS_TB F
INNER JOIN TAREA1.FIDE_ESTADOS_TB E
ON F.ID_ESTADO = E.ID_ESTADO
WHERE F.ID_FACTURA = P_ID_FACTURA;
V_ESTADO TAREA1.FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE;
BEGIN
OPEN C_ESTADO_FACTURA;
FETCH C_ESTADO_FACTURA INTO V_ESTADO;
IF C_ESTADO_FACTURA%NOTFOUND THEN
CLOSE C_ESTADO_FACTURA;
RETURN 'FACTURA NO ENCONTRADA';
END IF;
CLOSE C_ESTADO_FACTURA;
RETURN V_ESTADO;
EXCEPTION
WHEN OTHERS THEN
IF C_ESTADO_FACTURA%ISOPEN THEN
CLOSE C_ESTADO_FACTURA;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_ESTADO_FACTURA: ' || SQLERRM);
RETURN 'ERROR';
END FIDE_FN_ESTADO_FACTURA;

FUNCTION FIDE_FN_TOTAL_SERVICIOS_CITA(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE
) RETURN NUMBER IS
CURSOR C_TOTAL_SERVICIOS IS
SELECT NVL(SUM(PRECIO_APLICADO),0)
FROM TAREA1.FIDE_SERVICIOS_CITA_TB
WHERE ID_CITA = P_ID_CITA;
V_TOTAL NUMBER := 0;
BEGIN
OPEN C_TOTAL_SERVICIOS;
FETCH C_TOTAL_SERVICIOS INTO V_TOTAL;
CLOSE C_TOTAL_SERVICIOS;
RETURN NVL(V_TOTAL,0);
EXCEPTION
WHEN OTHERS THEN
IF C_TOTAL_SERVICIOS%ISOPEN THEN
CLOSE C_TOTAL_SERVICIOS;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_TOTAL_SERVICIOS_CITA: ' || SQLERRM);
RETURN 0;
END FIDE_FN_TOTAL_SERVICIOS_CITA;

FUNCTION FIDE_FN_TOTAL_PAGADO_CLIENTE(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
) RETURN NUMBER IS
CURSOR C_TOTAL_PAGADO IS
SELECT NVL(SUM(MONTO_TOTAL),0)
FROM TAREA1.FIDE_PAGOS_TB
WHERE ID_CLIENTE = P_ID_CLIENTE;
V_TOTAL NUMBER := 0;
BEGIN
OPEN C_TOTAL_PAGADO;
FETCH C_TOTAL_PAGADO INTO V_TOTAL;
CLOSE C_TOTAL_PAGADO;
RETURN NVL(V_TOTAL,0);
EXCEPTION
WHEN OTHERS THEN
IF C_TOTAL_PAGADO%ISOPEN THEN
CLOSE C_TOTAL_PAGADO;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_TOTAL_PAGADO_CLIENTE: ' || SQLERRM);
RETURN 0;
END FIDE_FN_TOTAL_PAGADO_CLIENTE;

FUNCTION FIDE_FN_SERVICIO_MAS_UTILIZADO
RETURN VARCHAR2 IS
CURSOR C_SERVICIO_MAS_UTILIZADO IS
SELECT NOMBRE
FROM (
SELECT S.NOMBRE, COUNT(*) AS CANTIDAD
FROM TAREA1.FIDE_SERVICIOS_CITA_TB SC
INNER JOIN TAREA1.FIDE_SERVICIOS_TB S
ON SC.ID_SERVICIO = S.ID_SERVICIO
GROUP BY S.NOMBRE
ORDER BY COUNT(*) DESC, S.NOMBRE ASC
)
WHERE ROWNUM = 1;
V_NOMBRE_SERVICIO TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE;
BEGIN
OPEN C_SERVICIO_MAS_UTILIZADO;
FETCH C_SERVICIO_MAS_UTILIZADO INTO V_NOMBRE_SERVICIO;
IF C_SERVICIO_MAS_UTILIZADO%NOTFOUND THEN
CLOSE C_SERVICIO_MAS_UTILIZADO;
RETURN 'SIN REGISTROS';
END IF;
CLOSE C_SERVICIO_MAS_UTILIZADO;
RETURN V_NOMBRE_SERVICIO;
EXCEPTION
WHEN OTHERS THEN
IF C_SERVICIO_MAS_UTILIZADO%ISOPEN THEN
CLOSE C_SERVICIO_MAS_UTILIZADO;
END IF;
DBMS_OUTPUT.PUT_LINE('Error en FIDE_FN_SERVICIO_MAS_UTILIZADO: ' || SQLERRM);
RETURN 'ERROR';
END FIDE_FN_SERVICIO_MAS_UTILIZADO;

END FIDE_TAREA3_PCK;
/