CREATE USER TAREA2 IDENTIFIED BY Password123456;
GRANT UNLIMITED TABLESPACE TO TAREA2; 
GRANT CREATE SESSION TO TAREA2;
GRANT CREATE TABLE TO TAREA2;
GRANT CREATE PROCEDURE TO TAREA2;
GRANT CREATE VIEW TO TAREA2;
GRANT CREATE SEQUENCE TO TAREA2;
GRANT CREATE TRIGGER TO TAREA2;

GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_ESTADOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CLIENTES_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_TELEFONOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CORREOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PROVINCIAS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CANTONES_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DISTRITOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DIRECCIONES_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_RAZA_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_MASCOTAS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CITAS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_CITA_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PAGOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PRODUCTOS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_VENTAS_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DETALLE_VENTA_TB TO TAREA2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_FACTURAS_TB TO TAREA2;

