CREATE TABLE FIDE_ESTADOS_TB (
  ID_ESTADO       NUMBER        NOT NULL,
  NOMBRE_ESTADO   VARCHAR2(50)  NOT NULL,
  DESCRIPCION     VARCHAR2(200),
  CONSTRAINT FIDE_ESTADOS_TB_PK PRIMARY KEY (ID_ESTADO),
  CONSTRAINT FIDE_ESTADOS_TB_UK1 UNIQUE (NOMBRE_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_PROVINCIAS_TB (
  ID_PROVINCIA      NUMBER         NOT NULL,
  NOMBRE_PROVINCIA  VARCHAR2(100)  NOT NULL,
  ID_ESTADO         NUMBER         NOT NULL,
  CONSTRAINT FIDE_PROVINCIAS_TB_PK PRIMARY KEY (ID_PROVINCIA),
  CONSTRAINT FIDE_PROVINCIAS_TB_FK1 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_CANTONES_TB (
  ID_CANTON      NUMBER         NOT NULL,
  ID_PROVINCIA   NUMBER         NOT NULL,
  NOMBRE_CANTON  VARCHAR2(100)  NOT NULL,
  ID_ESTADO      NUMBER         NOT NULL,
  CONSTRAINT FIDE_CANTONES_TB_PK PRIMARY KEY (ID_CANTON),
  CONSTRAINT FIDE_CANTONES_TB_FK1 FOREIGN KEY (ID_PROVINCIA)
    REFERENCES FIDE_PROVINCIAS_TB (ID_PROVINCIA),
  CONSTRAINT FIDE_CANTONES_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;



CREATE TABLE FIDE_DISTRITOS_TB (
  ID_DISTRITO      NUMBER         NOT NULL,
  ID_CANTON        NUMBER         NOT NULL,
  NOMBRE_DISTRITO  VARCHAR2(100)  NOT NULL,
  ID_ESTADO        NUMBER         NOT NULL,
  CONSTRAINT FIDE_DISTRITOS_TB_PK PRIMARY KEY (ID_DISTRITO),
  CONSTRAINT FIDE_DISTRITOS_TB_FK1 FOREIGN KEY (ID_CANTON)
    REFERENCES FIDE_CANTONES_TB (ID_CANTON),
  CONSTRAINT FIDE_DISTRITOS_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CLIENTES_TB (
  ID_CLIENTE       NUMBER         NOT NULL,
  NOMBRE           VARCHAR2(100)  NOT NULL,
  APELLIDO         VARCHAR2(100)  NOT NULL,
  FECHA_REGISTRO   DATE           NOT NULL,
  ID_ESTADO        NUMBER         NOT NULL,
  CONSTRAINT FIDE_CLIENTES_TB_PK PRIMARY KEY (ID_CLIENTE),
  CONSTRAINT FIDE_CLIENTES_TB_FK1 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_DIRECCIONES_TB (
  ID_DIRECCION      NUMBER          NOT NULL,
  ID_CLIENTE        NUMBER          NOT NULL,
  ID_PROVINCIA      NUMBER          NOT NULL,
  ID_CANTON         NUMBER          NOT NULL,
  ID_DISTRITO       NUMBER          NOT NULL,
  DIRECCION_EXACTA  VARCHAR2(300)   NOT NULL,
  ID_ESTADO         NUMBER          NOT NULL,
  CONSTRAINT FIDE_DIRECCIONES_TB_PK PRIMARY KEY (ID_DIRECCION),
  CONSTRAINT FIDE_DIRECCIONES_TB_FK1 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_DIRECCIONES_TB_FK2 FOREIGN KEY (ID_PROVINCIA)
    REFERENCES FIDE_PROVINCIAS_TB (ID_PROVINCIA),
  CONSTRAINT FIDE_DIRECCIONES_TB_FK3 FOREIGN KEY (ID_CANTON)
    REFERENCES FIDE_CANTONES_TB (ID_CANTON),
  CONSTRAINT FIDE_DIRECCIONES_TB_FK4 FOREIGN KEY (ID_DISTRITO)
    REFERENCES FIDE_DISTRITOS_TB (ID_DISTRITO),
  CONSTRAINT FIDE_DIRECCIONES_TB_FK5 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_TELEFONOS_TB (
  ID_TELEFONO    NUMBER        NOT NULL,
  ID_CLIENTE     NUMBER        NOT NULL,
  TELEFONO       VARCHAR2(20)  NOT NULL,
  TIPO_TELEFONO  VARCHAR2(20)  NOT NULL, -- Movil, Casa, Trabajo
  ID_ESTADO      NUMBER        NOT NULL,
  CONSTRAINT FIDE_TELEFONOS_TB_PK PRIMARY KEY (ID_TELEFONO),
  CONSTRAINT FIDE_TELEFONOS_TB_FK1 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_TELEFONOS_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_CORREOS_TB (
  ID_CORREO     NUMBER          NOT NULL,
  ID_CLIENTE    NUMBER          NOT NULL,
  CORREO        VARCHAR2(100)   NOT NULL,
  TIPO_CORREO   VARCHAR2(20)    NOT NULL, -- Personal, Trabajo
  ID_ESTADO     NUMBER          NOT NULL,
  CONSTRAINT FIDE_CORREOS_TB_PK PRIMARY KEY (ID_CORREO),
  CONSTRAINT FIDE_CORREOS_TB_UK1 UNIQUE (CORREO),
  CONSTRAINT FIDE_CORREOS_TB_FK1 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_CORREOS_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_MASCOTAS_TB (
  ID_MASCOTA      NUMBER         NOT NULL,
  ID_CLIENTE      NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(100)  NOT NULL,
  ESPECIE         VARCHAR2(50)   NOT NULL,
  RAZA            VARCHAR2(100),
  EDAD            NUMBER(3),
  PESO            NUMBER(5,2),
  OBSERVACIONES   VARCHAR2(500),
  ID_ESTADO       NUMBER         NOT NULL,
  CONSTRAINT FIDE_MASCOTAS_TB_PK PRIMARY KEY (ID_MASCOTA),
  CONSTRAINT FIDE_MASCOTAS_TB_FK1 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_MASCOTAS_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_SERVICIOS_TB (
  ID_SERVICIO      NUMBER         NOT NULL,
  NOMBRE           VARCHAR2(100)  NOT NULL,
  DESCRIPCION      VARCHAR2(300),
  PRECIO_ESTANDAR  NUMBER(10,2)   NOT NULL,
  DURACION_MIN     NUMBER(5)      NOT NULL,
  ID_ESTADO        NUMBER         NOT NULL,
  CONSTRAINT FIDE_SERVICIOS_TB_PK PRIMARY KEY (ID_SERVICIO),
  CONSTRAINT FIDE_SERVICIOS_TB_FK1 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_CITAS_TB (
  ID_CITA       NUMBER         NOT NULL,
  ID_MASCOTA    NUMBER         NOT NULL,
  ID_CLIENTE    NUMBER         NOT NULL,
  FECHA_CITA    DATE           NOT NULL,
  HORA_CITA     VARCHAR2(10)   NOT NULL,
  NOTAS_GROOMER VARCHAR2(500),
  ID_ESTADO     NUMBER         NOT NULL,
  CONSTRAINT FIDE_CITAS_TB_PK PRIMARY KEY (ID_CITA),
  CONSTRAINT FIDE_CITAS_TB_FK1 FOREIGN KEY (ID_MASCOTA)
    REFERENCES FIDE_MASCOTAS_TB (ID_MASCOTA),
  CONSTRAINT FIDE_CITAS_TB_FK2 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_CITAS_TB_FK3 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_SERVICIOS_CITA_TB (
  ID_CITA         NUMBER        NOT NULL,
  ID_SERVICIO     NUMBER        NOT NULL,
  PRECIO_APLICADO NUMBER(10,2)  NOT NULL,
  CONSTRAINT FIDE_SERVICIOS_CITA_TB_PK PRIMARY KEY (ID_CITA, ID_SERVICIO),
  CONSTRAINT FIDE_SERVICIOS_CITA_TB_FK1 FOREIGN KEY (ID_CITA)
    REFERENCES FIDE_CITAS_TB (ID_CITA),
  CONSTRAINT FIDE_SERVICIOS_CITA_TB_FK2 FOREIGN KEY (ID_SERVICIO)
    REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO)
) TABLESPACE DATA;


CREATE TABLE FIDE_METODOS_PAGO_TB (
  ID_METODO_PAGO  NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(50)   NOT NULL,
  DESCRIPCION     VARCHAR2(200),
  ID_ESTADO       NUMBER         NOT NULL,
  CONSTRAINT FIDE_METODOS_PAGO_TB_PK PRIMARY KEY (ID_METODO_PAGO),
  CONSTRAINT FIDE_METODOS_PAGO_TB_UK1 UNIQUE (NOMBRE),
  CONSTRAINT FIDE_METODOS_PAGO_TB_FK1 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_PAGOS_TB (
  ID_PAGO         NUMBER        NOT NULL,
  ID_CITA         NUMBER        NOT NULL,
  ID_CLIENTE      NUMBER        NOT NULL,
  FECHA_PAGO      DATE          NOT NULL,
  MONTO_TOTAL     NUMBER(10,2)  NOT NULL,
  ID_METODO_PAGO  NUMBER        NOT NULL,
  ID_ESTADO       NUMBER        NOT NULL,
  CONSTRAINT FIDE_PAGOS_TB_PK PRIMARY KEY (ID_PAGO),
  CONSTRAINT FIDE_PAGOS_TB_FK1 FOREIGN KEY (ID_CITA)
    REFERENCES FIDE_CITAS_TB (ID_CITA),
  CONSTRAINT FIDE_PAGOS_TB_FK2 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_PAGOS_TB_FK3 FOREIGN KEY (ID_METODO_PAGO)
    REFERENCES FIDE_METODOS_PAGO_TB (ID_METODO_PAGO),
  CONSTRAINT FIDE_PAGOS_TB_FK4 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_PRODUCTOS_TB (
  ID_PRODUCTO     NUMBER         NOT NULL,
  NOMBRE          VARCHAR2(100)  NOT NULL,
  DESCRIPCION     VARCHAR2(300),
  PRECIO_UNITARIO NUMBER(10,2)   NOT NULL,
  STOCK           NUMBER(10)     NOT NULL,
  ID_ESTADO       NUMBER         NOT NULL,
  CONSTRAINT FIDE_PRODUCTOS_TB_PK PRIMARY KEY (ID_PRODUCTO),
  CONSTRAINT FIDE_PRODUCTOS_TB_FK1 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


CREATE TABLE FIDE_VENTAS_TB (
  ID_VENTA     NUMBER        NOT NULL,
  ID_CLIENTE   NUMBER        NOT NULL,
  FECHA_VENTA  DATE          NOT NULL,
  TOTAL_VENTA  NUMBER(10,2)  NOT NULL,
  ID_ESTADO    NUMBER        NOT NULL,
  CONSTRAINT FIDE_VENTAS_TB_PK PRIMARY KEY (ID_VENTA),
  CONSTRAINT FIDE_VENTAS_TB_FK1 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_VENTAS_TB_FK2 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;

CREATE TABLE FIDE_DETALLE_VENTAS_TB (
  ID_VENTA        NUMBER        NOT NULL,
  ID_PRODUCTO     NUMBER        NOT NULL,
  CANTIDAD        NUMBER(5)     NOT NULL,
  PRECIO_UNITARIO NUMBER(10,2)  NOT NULL,
  SUBTOTAL        NUMBER(10,2)  NOT NULL,
  CONSTRAINT FIDE_DETALLE_VENTAS_TB_PK PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
  CONSTRAINT FIDE_DETALLE_VENTAS_TB_FK1 FOREIGN KEY (ID_VENTA)
    REFERENCES FIDE_VENTAS_TB (ID_VENTA),
  CONSTRAINT FIDE_DETALLE_VENTAS_TB_FK2 FOREIGN KEY (ID_PRODUCTO)
    REFERENCES FIDE_PRODUCTOS_TB (ID_PRODUCTO)
) TABLESPACE DATA;

CREATE TABLE FIDE_FACTURAS_TB (
  ID_FACTURA    NUMBER        NOT NULL,
  ID_VENTA      NUMBER        NOT NULL,
  ID_CLIENTE    NUMBER        NOT NULL,
  FECHA_EMISION DATE          NOT NULL,
  MONTO_TOTAL   NUMBER(10,2)  NOT NULL,
  ID_ESTADO     NUMBER        NOT NULL,
  CONSTRAINT FIDE_FACTURAS_TB_PK PRIMARY KEY (ID_FACTURA),
  CONSTRAINT FIDE_FACTURAS_TB_FK1 FOREIGN KEY (ID_VENTA)
    REFERENCES FIDE_VENTAS_TB (ID_VENTA),
  CONSTRAINT FIDE_FACTURAS_TB_FK2 FOREIGN KEY (ID_CLIENTE)
    REFERENCES FIDE_CLIENTES_TB (ID_CLIENTE),
  CONSTRAINT FIDE_FACTURAS_TB_FK3 FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
) TABLESPACE DATA;


SELECT table_name, tablespace_name
FROM user_tables
WHERE table_name LIKE 'FIDE_%_TB'
ORDER BY table_name;

INSERT INTO FIDE_ESTADOS_TB VALUES (1,'ACTIVO','Registro vigente');
INSERT INTO FIDE_ESTADOS_TB VALUES (2,'INACTIVO','Registro no vigente');
INSERT INTO FIDE_ESTADOS_TB VALUES (3,'PENDIENTE','Pendiente de proceso');
INSERT INTO FIDE_ESTADOS_TB VALUES (4,'COMPLETADO','Proceso completado');
INSERT INTO FIDE_ESTADOS_TB VALUES (5,'CANCELADO','Proceso cancelado');
INSERT INTO FIDE_ESTADOS_TB VALUES (6,'ANULADO','Registro anulado');
INSERT INTO FIDE_ESTADOS_TB VALUES (7,'EN_PROCESO','En proceso');
INSERT INTO FIDE_ESTADOS_TB VALUES (8,'AGOTADO','Sin stock');
INSERT INTO FIDE_ESTADOS_TB VALUES (9,'PAGADO','Pago aplicado');
INSERT INTO FIDE_ESTADOS_TB VALUES (10,'NO_PAGADO','Pago pendiente');
INSERT INTO FIDE_ESTADOS_TB VALUES (11,'EMITIDA','Factura emitida');
INSERT INTO FIDE_ESTADOS_TB VALUES (12,'PEND_FACT','Factura pendiente');
INSERT INTO FIDE_ESTADOS_TB VALUES (13,'CANC_FACT','Factura cancelada');
INSERT INTO FIDE_ESTADOS_TB VALUES (14,'CONFIRMADA','Cita confirmada');
INSERT INTO FIDE_ESTADOS_TB VALUES (15,'REPROGRAMADA','Cita reprogramada');
INSERT INTO FIDE_ESTADOS_TB VALUES (16,'FALLECIDA','Mascota fallecida');
INSERT INTO FIDE_ESTADOS_TB VALUES (17,'BLOQUEADO','Registro bloqueado');
INSERT INTO FIDE_ESTADOS_TB VALUES (18,'SUSPENDIDO','Registro suspendido');
INSERT INTO FIDE_ESTADOS_TB VALUES (19,'DEVUELTO','Venta devuelta');
INSERT INTO FIDE_ESTADOS_TB VALUES (20,'RECHAZADO','Solicitud rechazada');
COMMIT;
INSERT INTO FIDE_PROVINCIAS_TB VALUES (1,'San Jose',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (2,'Alajuela',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (3,'Cartago',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (4,'Heredia',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (5,'Guanacaste',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (6,'Puntarenas',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (7,'Limon',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (8,'Prov_08',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (9,'Prov_09',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (10,'Prov_10',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (11,'Prov_11',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (12,'Prov_12',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (13,'Prov_13',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (14,'Prov_14',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (15,'Prov_15',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (16,'Prov_16',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (17,'Prov_17',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (18,'Prov_18',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (19,'Prov_19',1);
INSERT INTO FIDE_PROVINCIAS_TB VALUES (20,'Prov_20',1);
COMMIT;
INSERT INTO FIDE_CANTONES_TB VALUES (1,1,'Canton_01',1);
INSERT INTO FIDE_CANTONES_TB VALUES (2,2,'Canton_02',1);
INSERT INTO FIDE_CANTONES_TB VALUES (3,3,'Canton_03',1);
INSERT INTO FIDE_CANTONES_TB VALUES (4,4,'Canton_04',1);
INSERT INTO FIDE_CANTONES_TB VALUES (5,5,'Canton_05',1);
INSERT INTO FIDE_CANTONES_TB VALUES (6,6,'Canton_06',1);
INSERT INTO FIDE_CANTONES_TB VALUES (7,7,'Canton_07',1);
INSERT INTO FIDE_CANTONES_TB VALUES (8,8,'Canton_08',1);
INSERT INTO FIDE_CANTONES_TB VALUES (9,9,'Canton_09',1);
INSERT INTO FIDE_CANTONES_TB VALUES (10,10,'Canton_10',1);
INSERT INTO FIDE_CANTONES_TB VALUES (11,11,'Canton_11',1);
INSERT INTO FIDE_CANTONES_TB VALUES (12,12,'Canton_12',1);
INSERT INTO FIDE_CANTONES_TB VALUES (13,13,'Canton_13',1);
INSERT INTO FIDE_CANTONES_TB VALUES (14,14,'Canton_14',1);
INSERT INTO FIDE_CANTONES_TB VALUES (15,15,'Canton_15',1);
INSERT INTO FIDE_CANTONES_TB VALUES (16,16,'Canton_16',1);
INSERT INTO FIDE_CANTONES_TB VALUES (17,17,'Canton_17',1);
INSERT INTO FIDE_CANTONES_TB VALUES (18,18,'Canton_18',1);
INSERT INTO FIDE_CANTONES_TB VALUES (19,19,'Canton_19',1);
INSERT INTO FIDE_CANTONES_TB VALUES (20,20,'Canton_20',1);
COMMIT;
INSERT INTO FIDE_DISTRITOS_TB VALUES (1,1,'Distrito_01',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (2,2,'Distrito_02',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (3,3,'Distrito_03',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (4,4,'Distrito_04',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (5,5,'Distrito_05',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (6,6,'Distrito_06',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (7,7,'Distrito_07',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (8,8,'Distrito_08',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (9,9,'Distrito_09',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (10,10,'Distrito_10',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (11,11,'Distrito_11',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (12,12,'Distrito_12',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (13,13,'Distrito_13',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (14,14,'Distrito_14',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (15,15,'Distrito_15',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (16,16,'Distrito_16',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (17,17,'Distrito_17',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (18,18,'Distrito_18',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (19,19,'Distrito_19',1);
INSERT INTO FIDE_DISTRITOS_TB VALUES (20,20,'Distrito_20',1);
COMMIT;
INSERT INTO FIDE_CLIENTES_TB VALUES (1,'Cliente1','Apellido1',SYSDATE-60,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (2,'Cliente2','Apellido2',SYSDATE-59,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (3,'Cliente3','Apellido3',SYSDATE-58,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (4,'Cliente4','Apellido4',SYSDATE-57,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (5,'Cliente5','Apellido5',SYSDATE-56,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (6,'Cliente6','Apellido6',SYSDATE-55,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (7,'Cliente7','Apellido7',SYSDATE-54,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (8,'Cliente8','Apellido8',SYSDATE-53,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (9,'Cliente9','Apellido9',SYSDATE-52,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (10,'Cliente10','Apellido10',SYSDATE-51,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (11,'Cliente11','Apellido11',SYSDATE-50,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (12,'Cliente12','Apellido12',SYSDATE-49,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (13,'Cliente13','Apellido13',SYSDATE-48,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (14,'Cliente14','Apellido14',SYSDATE-47,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (15,'Cliente15','Apellido15',SYSDATE-46,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (16,'Cliente16','Apellido16',SYSDATE-45,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (17,'Cliente17','Apellido17',SYSDATE-44,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (18,'Cliente18','Apellido18',SYSDATE-43,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (19,'Cliente19','Apellido19',SYSDATE-42,1);
INSERT INTO FIDE_CLIENTES_TB VALUES (20,'Cliente20','Apellido20',SYSDATE-41,1);
COMMIT;
INSERT INTO FIDE_DIRECCIONES_TB VALUES (1,1,1,1,1,'Direccion exacta 1',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (2,2,2,2,2,'Direccion exacta 2',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (3,3,3,3,3,'Direccion exacta 3',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (4,4,4,4,4,'Direccion exacta 4',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (5,5,5,5,5,'Direccion exacta 5',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (6,6,6,6,6,'Direccion exacta 6',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (7,7,7,7,7,'Direccion exacta 7',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (8,8,8,8,8,'Direccion exacta 8',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (9,9,9,9,9,'Direccion exacta 9',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (10,10,10,10,10,'Direccion exacta 10',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (11,11,11,11,11,'Direccion exacta 11',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (12,12,12,12,12,'Direccion exacta 12',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (13,13,13,13,13,'Direccion exacta 13',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (14,14,14,14,14,'Direccion exacta 14',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (15,15,15,15,15,'Direccion exacta 15',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (16,16,16,16,16,'Direccion exacta 16',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (17,17,17,17,17,'Direccion exacta 17',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (18,18,18,18,18,'Direccion exacta 18',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (19,19,19,19,19,'Direccion exacta 19',1);
INSERT INTO FIDE_DIRECCIONES_TB VALUES (20,20,20,20,20,'Direccion exacta 20',1);
COMMIT;
INSERT INTO FIDE_TELEFONOS_TB VALUES (1,1,'8888-0001','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (2,2,'8888-0002','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (3,3,'8888-0003','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (4,4,'8888-0004','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (5,5,'8888-0005','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (6,6,'8888-0006','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (7,7,'8888-0007','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (8,8,'8888-0008','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (9,9,'8888-0009','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (10,10,'8888-0010','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (11,11,'8888-0011','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (12,12,'8888-0012','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (13,13,'8888-0013','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (14,14,'8888-0014','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (15,15,'8888-0015','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (16,16,'8888-0016','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (17,17,'8888-0017','Casa',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (18,18,'8888-0018','Trabajo',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (19,19,'8888-0019','Movil',1);
INSERT INTO FIDE_TELEFONOS_TB VALUES (20,20,'8888-0020','Casa',1);
COMMIT;
INSERT INTO FIDE_CORREOS_TB VALUES (1,1,'cliente1@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (2,2,'cliente2@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (3,3,'cliente3@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (4,4,'cliente4@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (5,5,'cliente5@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (6,6,'cliente6@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (7,7,'cliente7@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (8,8,'cliente8@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (9,9,'cliente9@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (10,10,'cliente10@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (11,11,'cliente11@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (12,12,'cliente12@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (13,13,'cliente13@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (14,14,'cliente14@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (15,15,'cliente15@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (16,16,'cliente16@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (17,17,'cliente17@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (18,18,'cliente18@mail.com','Trabajo',1);
INSERT INTO FIDE_CORREOS_TB VALUES (19,19,'cliente19@mail.com','Personal',1);
INSERT INTO FIDE_CORREOS_TB VALUES (20,20,'cliente20@mail.com','Trabajo',1);
COMMIT;
INSERT INTO FIDE_MASCOTAS_TB VALUES (1,1,'Max','Perro','Labrador',3,18.50,'Ninguna',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (2,2,'Luna','Perro','Poodle',2,7.20,'Ansiosa',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (3,3,'Rocky','Perro','Bulldog',4,22.10,'Dermatitis leve',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (4,4,'Nala','Gato','Siames',1,3.90,'Asustadiza',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (5,5,'Toby','Perro','Beagle',5,12.40,'Alergias',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (6,6,'Milo','Perro','Shih Tzu',2,6.80,'Control dental',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (7,7,'Kira','Perro','Pastor Aleman',6,28.00,'Entrenamiento',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (8,8,'Simba','Gato','Mestizo',3,4.10,'Ninguna',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (9,9,'Bobby','Perro','Boxer',4,24.60,'Energético',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (10,10,'Coco','Perro','Chihuahua',2,2.50,'Nervioso',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (11,11,'Zeus','Perro','Husky',3,26.30,'Pelo abundante',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (12,12,'Maya','Gato','Persa',5,4.80,'Lagrimeo',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (13,13,'Bruno','Perro','Golden',2,19.70,'Ninguna',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (14,14,'Daisy','Perro','Cocker',6,13.20,'Otitis recurrente',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (15,15,'Thor','Perro','Doberman',4,30.10,'Ninguna',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (16,16,'Kiwi','Ave','Periquito',1,0.15,'Revisión general',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (17,17,'Loki','Perro','Mestizo',7,16.90,'Artritis',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (18,18,'Sasha','Perro','Pug',3,9.40,'Sobrepeso',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (19,19,'Michi','Gato','Mestizo',2,3.60,'Ninguna',1);
INSERT INTO FIDE_MASCOTAS_TB VALUES (20,20,'Firulais','Perro','Mestizo',8,14.30,'Control senior',1);
COMMIT;
INSERT INTO FIDE_SERVICIOS_TB VALUES (1,'Bano','Bano completo',15000,45,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (2,'Corte Pelo','Corte de pelo estandar',18000,60,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (3,'Corte Unas','Corte de unas',8000,20,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (4,'Limpieza Oidos','Limpieza de oidos',7000,15,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (5,'Deslanado','Retiro de pelo muerto',20000,50,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (6,'Cepillado','Cepillado profundo',9000,25,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (7,'Perfume','Aplicacion de perfume',3000,5,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (8,'Higiene Dental','Limpieza dental basica',12000,30,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (9,'Tratamiento Piel','Shampoo medicado',22000,55,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (10,'Corte Raza','Corte segun raza',25000,75,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (11,'Bano Premium','Bano con productos premium',28000,60,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (12,'Spa Patas','Hidratacion de patas',6000,15,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (13,'Limpieza Ojos','Limpieza de ojos',5000,10,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (14,'Corte Higienico','Corte higienico',10000,20,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (15,'Secado','Secado profesional',8000,25,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (16,'Peinado','Peinado y acabado',7000,20,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (17,'Antipulgas','Tratamiento antipulgas',18000,30,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (18,'Mascarilla','Mascarilla hidratante',9000,15,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (19,'Corte Express','Corte rapido',12000,30,1);
INSERT INTO FIDE_SERVICIOS_TB VALUES (20,'Consulta','Consulta grooming',5000,10,1);
COMMIT;
INSERT INTO FIDE_CITAS_TB VALUES (1,1,1,SYSDATE-20,'09:00','Nota 1',14);
INSERT INTO FIDE_CITAS_TB VALUES (2,2,2,SYSDATE-19,'10:00','Nota 2',14);
INSERT INTO FIDE_CITAS_TB VALUES (3,3,3,SYSDATE-18,'11:00','Nota 3',4);
INSERT INTO FIDE_CITAS_TB VALUES (4,4,4,SYSDATE-17,'12:00','Nota 4',5);
INSERT INTO FIDE_CITAS_TB VALUES (5,5,5,SYSDATE-16,'13:00','Nota 5',14);
INSERT INTO FIDE_CITAS_TB VALUES (6,6,6,SYSDATE-15,'14:00','Nota 6',4);
INSERT INTO FIDE_CITAS_TB VALUES (7,7,7,SYSDATE-14,'15:00','Nota 7',14);
INSERT INTO FIDE_CITAS_TB VALUES (8,8,8,SYSDATE-13,'16:00','Nota 8',7);
INSERT INTO FIDE_CITAS_TB VALUES (9,9,9,SYSDATE-12,'09:30','Nota 9',4);
INSERT INTO FIDE_CITAS_TB VALUES (10,10,10,SYSDATE-11,'10:30','Nota 10',14);
INSERT INTO FIDE_CITAS_TB VALUES (11,11,11,SYSDATE-10,'11:30','Nota 11',4);
INSERT INTO FIDE_CITAS_TB VALUES (12,12,12,SYSDATE-9,'12:30','Nota 12',5);
INSERT INTO FIDE_CITAS_TB VALUES (13,13,13,SYSDATE-8,'13:30','Nota 13',14);
INSERT INTO FIDE_CITAS_TB VALUES (14,14,14,SYSDATE-7,'14:30','Nota 14',4);
INSERT INTO FIDE_CITAS_TB VALUES (15,15,15,SYSDATE-6,'15:30','Nota 15',14);
INSERT INTO FIDE_CITAS_TB VALUES (16,16,16,SYSDATE-5,'16:30','Nota 16',7);
INSERT INTO FIDE_CITAS_TB VALUES (17,17,17,SYSDATE-4,'09:15','Nota 17',14);
INSERT INTO FIDE_CITAS_TB VALUES (18,18,18,SYSDATE-3,'10:15','Nota 18',4);
INSERT INTO FIDE_CITAS_TB VALUES (19,19,19,SYSDATE-2,'11:15','Nota 19',14);
INSERT INTO FIDE_CITAS_TB VALUES (20,20,20,SYSDATE-1,'12:15','Nota 20',4);
COMMIT;
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (1,1,15000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (2,2,18000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (3,3,8000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (4,4,7000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (5,5,20000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (6,6,9000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (7,7,3000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (8,8,12000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (9,9,22000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (10,10,25000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (11,11,28000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (12,12,6000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (13,13,5000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (14,14,10000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (15,15,8000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (16,16,7000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (17,17,18000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (18,18,9000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (19,19,12000);
INSERT INTO FIDE_SERVICIOS_CITA_TB VALUES (20,20,5000);
COMMIT;
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (1,'Efectivo','Pago en efectivo',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (2,'Tarjeta Debito','Pago con debito',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (3,'Tarjeta Credito','Pago con credito',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (4,'Transferencia','Pago por transferencia',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (5,'SINPE','Pago SINPE',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (6,'Cheque','Pago con cheque',2);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (7,'PayPal','Pago PayPal',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (8,'Apple Pay','Pago Apple Pay',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (9,'Google Pay','Pago Google Pay',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (10,'Crypto','Pago cripto',2);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (11,'Vales','Pago con vales',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (12,'Cuotas','Pago en cuotas',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (13,'Mixto','Pago mixto',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (14,'Bizum','Metodo ejemplo',2);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (15,'Deposito','Deposito bancario',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (16,'Link Pago','Link de pago',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (17,'POS','Pago por POS',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (18,'QR','Pago QR',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (19,'Credito Interno','Saldo interno',1);
INSERT INTO FIDE_METODOS_PAGO_TB VALUES (20,'Otro','Otro metodo',1);
COMMIT;
INSERT INTO FIDE_PAGOS_TB VALUES (1,1,1,SYSDATE-19,15000,1,9);
INSERT INTO FIDE_PAGOS_TB VALUES (2,2,2,SYSDATE-18,18000,2,9);
INSERT INTO FIDE_PAGOS_TB VALUES (3,3,3,SYSDATE-17,8000,3,9);
INSERT INTO FIDE_PAGOS_TB VALUES (4,4,4,SYSDATE-16,7000,4,5);
INSERT INTO FIDE_PAGOS_TB VALUES (5,5,5,SYSDATE-15,20000,5,9);
INSERT INTO FIDE_PAGOS_TB VALUES (6,6,6,SYSDATE-14,9000,1,10);
INSERT INTO FIDE_PAGOS_TB VALUES (7,7,7,SYSDATE-13,3000,2,9);
INSERT INTO FIDE_PAGOS_TB VALUES (8,8,8,SYSDATE-12,12000,3,9);
INSERT INTO FIDE_PAGOS_TB VALUES (9,9,9,SYSDATE-11,22000,4,9);
INSERT INTO FIDE_PAGOS_TB VALUES (10,10,10,SYSDATE-10,25000,5,9);
INSERT INTO FIDE_PAGOS_TB VALUES (11,11,11,SYSDATE-9,28000,1,9);
INSERT INTO FIDE_PAGOS_TB VALUES (12,12,12,SYSDATE-8,6000,2,5);
INSERT INTO FIDE_PAGOS_TB VALUES (13,13,13,SYSDATE-7,5000,3,9);
INSERT INTO FIDE_PAGOS_TB VALUES (14,14,14,SYSDATE-6,10000,4,9);
INSERT INTO FIDE_PAGOS_TB VALUES (15,15,15,SYSDATE-5,8000,5,9);
INSERT INTO FIDE_PAGOS_TB VALUES (16,16,16,SYSDATE-4,7000,1,9);
INSERT INTO FIDE_PAGOS_TB VALUES (17,17,17,SYSDATE-3,18000,2,10);
INSERT INTO FIDE_PAGOS_TB VALUES (18,18,18,SYSDATE-2,9000,3,9);
INSERT INTO FIDE_PAGOS_TB VALUES (19,19,19,SYSDATE-1,12000,4,9);
INSERT INTO FIDE_PAGOS_TB VALUES (20,20,20,SYSDATE,5000,5,9);
COMMIT;
INSERT INTO FIDE_PRODUCTOS_TB VALUES (1,'Shampoo','Shampoo para perro',6500,40,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (2,'Collar','Collar ajustable',4500,50,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (3,'Premios','Snacks',3500,80,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (4,'Cepillo','Cepillo grooming',7000,25,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (5,'Cortaunas','Cortaunas',6000,15,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (6,'Toalla','Toalla absorbente',5000,30,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (7,'Perfume','Perfume mascota',5500,20,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (8,'Antipulgas','Pipeta antipulgas',9000,10,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (9,'Shampoo Med','Medicado',8500,12,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (10,'Cama','Cama pequeña',18000,8,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (11,'Juguete','Juguete goma',4000,60,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (12,'Arnes','Arnes mediano',12000,18,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (13,'Peine','Peine metal',6500,22,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (14,'Balsamo','Balsamo pelo',7500,9,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (15,'Spray','Spray desenredante',8000,14,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (16,'Hueso','Hueso snack',2500,100,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (17,'Bebedero','Bebedero',3000,35,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (18,'Comedero','Comedero',3200,33,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (19,'Guantes','Guantes cepillado',5800,11,1);
INSERT INTO FIDE_PRODUCTOS_TB VALUES (20,'Kit Groom','Kit completo',25000,5,1);
COMMIT;
INSERT INTO FIDE_VENTAS_TB VALUES (1,1,SYSDATE-30,6500,4);
INSERT INTO FIDE_VENTAS_TB VALUES (2,2,SYSDATE-29,9000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (3,3,SYSDATE-28,7000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (4,4,SYSDATE-27,18000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (5,5,SYSDATE-26,4000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (6,6,SYSDATE-25,12000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (7,7,SYSDATE-24,2500,7);
INSERT INTO FIDE_VENTAS_TB VALUES (8,8,SYSDATE-23,5000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (9,9,SYSDATE-22,5500,4);
INSERT INTO FIDE_VENTAS_TB VALUES (10,10,SYSDATE-21,9000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (11,11,SYSDATE-20,8500,4);
INSERT INTO FIDE_VENTAS_TB VALUES (12,12,SYSDATE-19,5800,4);
INSERT INTO FIDE_VENTAS_TB VALUES (13,13,SYSDATE-18,3200,4);
INSERT INTO FIDE_VENTAS_TB VALUES (14,14,SYSDATE-17,3000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (15,15,SYSDATE-16,25000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (16,16,SYSDATE-15,3500,7);
INSERT INTO FIDE_VENTAS_TB VALUES (17,17,SYSDATE-14,4500,4);
INSERT INTO FIDE_VENTAS_TB VALUES (18,18,SYSDATE-13,6500,4);
INSERT INTO FIDE_VENTAS_TB VALUES (19,19,SYSDATE-12,8000,4);
INSERT INTO FIDE_VENTAS_TB VALUES (20,20,SYSDATE-11,18000,4);
COMMIT;
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (1,1,1,6500,6500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (2,2,2,4500,9000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (3,3,2,3500,7000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (4,10,1,18000,18000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (5,11,1,4000,4000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (6,12,1,12000,12000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (7,16,1,2500,2500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (8,6,1,5000,5000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (9,7,1,5500,5500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (10,8,1,9000,9000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (11,9,1,8500,8500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (12,19,1,5800,5800);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (13,18,1,3200,3200);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (14,17,1,3000,3000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (15,20,1,25000,25000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (16,3,1,3500,3500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (17,2,1,4500,4500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (18,1,1,6500,6500);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (19,15,1,8000,8000);
INSERT INTO FIDE_DETALLE_VENTAS_TB VALUES (20,10,1,18000,18000);
COMMIT;
INSERT INTO FIDE_FACTURAS_TB VALUES (1,1,1,SYSDATE-30,6500,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (2,2,2,SYSDATE-29,9000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (3,3,3,SYSDATE-28,7000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (4,4,4,SYSDATE-27,18000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (5,5,5,SYSDATE-26,4000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (6,6,6,SYSDATE-25,12000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (7,7,7,SYSDATE-24,2500,12);
INSERT INTO FIDE_FACTURAS_TB VALUES (8,8,8,SYSDATE-23,5000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (9,9,9,SYSDATE-22,5500,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (10,10,10,SYSDATE-21,9000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (11,11,11,SYSDATE-20,8500,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (12,12,12,SYSDATE-19,5800,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (13,13,13,SYSDATE-18,3200,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (14,14,14,SYSDATE-17,3000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (15,15,15,SYSDATE-16,25000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (16,16,16,SYSDATE-15,3500,12);
INSERT INTO FIDE_FACTURAS_TB VALUES (17,17,17,SYSDATE-14,4500,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (18,18,18,SYSDATE-13,6500,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (19,19,19,SYSDATE-12,8000,11);
INSERT INTO FIDE_FACTURAS_TB VALUES (20,20,20,SYSDATE-11,18000,11);
COMMIT;

SELECT 'FIDE_ESTADOS_TB' tabla, COUNT(*) total FROM FIDE_ESTADOS_TB
UNION ALL SELECT 'FIDE_PROVINCIAS_TB', COUNT(*) FROM FIDE_PROVINCIAS_TB
UNION ALL SELECT 'FIDE_CANTONES_TB', COUNT(*) FROM FIDE_CANTONES_TB
UNION ALL SELECT 'FIDE_DISTRITOS_TB', COUNT(*) FROM FIDE_DISTRITOS_TB
UNION ALL SELECT 'FIDE_CLIENTES_TB', COUNT(*) FROM FIDE_CLIENTES_TB
UNION ALL SELECT 'FIDE_DIRECCIONES_TB', COUNT(*) FROM FIDE_DIRECCIONES_TB
UNION ALL SELECT 'FIDE_TELEFONOS_TB', COUNT(*) FROM FIDE_TELEFONOS_TB
UNION ALL SELECT 'FIDE_CORREOS_TB', COUNT(*) FROM FIDE_CORREOS_TB
UNION ALL SELECT 'FIDE_MASCOTAS_TB', COUNT(*) FROM FIDE_MASCOTAS_TB
UNION ALL SELECT 'FIDE_SERVICIOS_TB', COUNT(*) FROM FIDE_SERVICIOS_TB
UNION ALL SELECT 'FIDE_CITAS_TB', COUNT(*) FROM FIDE_CITAS_TB
UNION ALL SELECT 'FIDE_SERVICIOS_CITA_TB', COUNT(*) FROM FIDE_SERVICIOS_CITA_TB
UNION ALL SELECT 'FIDE_METODOS_PAGO_TB', COUNT(*) FROM FIDE_METODOS_PAGO_TB
UNION ALL SELECT 'FIDE_PAGOS_TB', COUNT(*) FROM FIDE_PAGOS_TB
UNION ALL SELECT 'FIDE_PRODUCTOS_TB', COUNT(*) FROM FIDE_PRODUCTOS_TB
UNION ALL SELECT 'FIDE_VENTAS_TB', COUNT(*) FROM FIDE_VENTAS_TB
UNION ALL SELECT 'FIDE_DETALLE_VENTAS_TB', COUNT(*) FROM FIDE_DETALLE_VENTAS_TB
UNION ALL SELECT 'FIDE_FACTURAS_TB', COUNT(*) FROM FIDE_FACTURAS_TB
ORDER BY tabla;

