CREATE USER TAREA4 IDENTIFIED BY Password123456;
COMMIT;

GRANT CREATE SESSION TO TAREA4;
GRANT CREATE TABLE TO TAREA4;
GRANT CREATE VIEW TO TAREA4;
GRANT CREATE PROCEDURE TO TAREA4;
GRANT CREATE SEQUENCE TO TAREA4;
GRANT CREATE TRIGGER TO TAREA4;
GRANT CREATE SYNONYM TO TAREA4;
GRANT UNLIMITED TABLESPACE TO TAREA4;

GRANT ALTER ANY TABLE TO TAREA4;
GRANT CREATE ANY TRIGGER TO TAREA4;
GRANT CREATE ANY SEQUENCE TO TAREA4;
GRANT CREATE ANY PROCEDURE TO TAREA4;
GRANT SELECT ANY TABLE TO TAREA4;
COMMIT;

GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CANTONES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CITAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CLIENTES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CORREOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DETALLE_VENTA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DIRECCIONES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DISTRITOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_ESTADOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_FACTURAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_MASCOTAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PAGOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PRODUCTOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PROVINCIAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_RAZA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_CITA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_TELEFONOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_VENTAS_TB TO TAREA4;
COMMIT;

ALTER TABLE TAREA1.FIDE_CANTONES_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_CITAS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_CLIENTES_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_CORREOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_DETALLE_VENTA_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_DIRECCIONES_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_DISTRITOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_ESTADOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_FACTURAS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_MASCOTAS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_PAGOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_PRODUCTOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_PROVINCIAS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_RAZA_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_SERVICIOS_CITA_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_SERVICIOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_TELEFONOS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

ALTER TABLE TAREA1.FIDE_VENTAS_TB ADD (
USUARIO_CREACION VARCHAR2(100),
FECHA_CREACION DATE,
USUARIO_MODIFICACION VARCHAR2(100),
FECHA_MODIFICACION DATE
);

commit;

CREATE SEQUENCE TAREA1.SEQ_FIDE_ESTADOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PROVINCIAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CANTONES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_DISTRITOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CLIENTES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_DIRECCIONES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_TELEFONOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CORREOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_RAZA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_MASCOTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CITAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_SERVICIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PAGOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PRODUCTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_VENTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_FACTURAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER SEQUENCE TAREA1.SEQ_FIDE_ESTADOS INCREMENT BY 6;
SELECT TAREA1.SEQ_FIDE_ESTADOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_ESTADOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_ESTADOS INCREMENT BY 6;
SELECT TAREA1.SEQ_FIDE_ESTADOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_ESTADOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PROVINCIAS INCREMENT BY 1;
SELECT TAREA1.SEQ_FIDE_PROVINCIAS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PROVINCIAS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CANTONES INCREMENT BY 2;
SELECT TAREA1.SEQ_FIDE_CANTONES.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CANTONES INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_DISTRITOS INCREMENT BY 2;
SELECT TAREA1.SEQ_FIDE_DISTRITOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_DISTRITOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CLIENTES INCREMENT BY 20;
SELECT TAREA1.SEQ_FIDE_CLIENTES.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CLIENTES INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_TELEFONOS INCREMENT BY 20;
SELECT TAREA1.SEQ_FIDE_TELEFONOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_TELEFONOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_RAZA INCREMENT BY 5;
SELECT TAREA1.SEQ_FIDE_RAZA.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_RAZA INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_MASCOTAS INCREMENT BY 20;
SELECT TAREA1.SEQ_FIDE_MASCOTAS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CITAS INCREMENT BY 20;
SELECT TAREA1.SEQ_FIDE_CITAS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_CITAS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_SERVICIOS INCREMENT BY 5;
SELECT TAREA1.SEQ_FIDE_SERVICIOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_SERVICIOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PAGOS INCREMENT BY 20;
SELECT TAREA1.SEQ_FIDE_PAGOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PAGOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PRODUCTOS INCREMENT BY 30;
SELECT TAREA1.SEQ_FIDE_PRODUCTOS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_PRODUCTOS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_VENTAS INCREMENT BY 50;
SELECT TAREA1.SEQ_FIDE_VENTAS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_VENTAS INCREMENT BY 1;
ALTER SEQUENCE TAREA1.SEQ_FIDE_FACTURAS INCREMENT BY 50;
SELECT TAREA1.SEQ_FIDE_FACTURAS.NEXTVAL FROM DUAL;
ALTER SEQUENCE TAREA1.SEQ_FIDE_FACTURAS INCREMENT BY 1;




CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_ESTADOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_ESTADO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_ESTADOS.NEXTVAL
INTO :NEW.ID_ESTADO
FROM DUAL;
END IF;

:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;

IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/


CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PROVINCIAS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_PROVINCIA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_PROVINCIAS.NEXTVAL INTO :NEW.ID_PROVINCIA FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CANTONES_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_CANTON IS NULL THEN
SELECT TAREA1.SEQ_FIDE_CANTONES.NEXTVAL INTO :NEW.ID_CANTON FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_DISTRITOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_DISTRITO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_DISTRITOS.NEXTVAL INTO :NEW.ID_DISTRITO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CLIENTES_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_CLIENTE IS NULL THEN
SELECT TAREA1.SEQ_FIDE_CLIENTES.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_DIRECCIONES_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_DIRECCION IS NULL THEN
SELECT TAREA1.SEQ_FIDE_DIRECCIONES.NEXTVAL INTO :NEW.ID_DIRECCION FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_TELEFONOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_TELEFONO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_TELEFONOS.NEXTVAL INTO :NEW.ID_TELEFONO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CORREOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_CORREOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_CORREO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_CORREOS.NEXTVAL INTO :NEW.ID_CORREO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_RAZA_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_RAZA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_RAZA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_RAZA.NEXTVAL INTO :NEW.ID_RAZA FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_MASCOTAS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_MASCOTAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_MASCOTA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_MASCOTAS.NEXTVAL INTO :NEW.ID_MASCOTA FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CITAS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_CITAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_CITA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_CITAS.NEXTVAL INTO :NEW.ID_CITA FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_SERVICIOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_SERVICIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_SERVICIO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_SERVICIOS.NEXTVAL INTO :NEW.ID_SERVICIO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PAGOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_PAGOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_PAGO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_PAGOS.NEXTVAL INTO :NEW.ID_PAGO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PRODUCTOS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_PRODUCTO IS NULL THEN
SELECT TAREA1.SEQ_FIDE_PRODUCTOS.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_VENTAS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_VENTAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
IF :NEW.ID_VENTA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_VENTAS.NEXTVAL INTO :NEW.ID_VENTA FROM DUAL;
END IF;
:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;
END;
/
CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_FACTURAS_BI_BU
BEFORE INSERT OR UPDATE ON TAREA1.FIDE_FACTURAS_TB
FOR EACH ROW
DECLARE
V_ANO VARCHAR2(4);
V_NUM NUMBER;
BEGIN
IF INSERTING THEN

V_ANO := TO_CHAR(SYSDATE, 'YYYY');

IF :NEW.ID_FACTURA IS NULL THEN
SELECT TAREA1.SEQ_FIDE_FACTURAS.NEXTVAL INTO V_NUM FROM DUAL;

:NEW.ID_FACTURA := TO_NUMBER(V_ANO || LPAD(V_NUM, 8, '0'));
END IF;

:NEW.USUARIO_CREACION := USER;
:NEW.FECHA_CREACION := SYSDATE;
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;

END IF;

IF UPDATING THEN
:NEW.USUARIO_MODIFICACION := USER;
:NEW.FECHA_MODIFICACION := SYSDATE;
END IF;

END;
/
commit;

INSERT INTO TAREA1.FIDE_FACTURAS_TB (
ID_VENTA,
ID_CLIENTE,
FECHA_EMISION,
MONTO_TOTAL,
ID_ESTADO
) VALUES (
1,
1,
SYSDATE,
1000,
1
);

SELECT ID_FACTURA, FECHA_EMISION
FROM TAREA1.FIDE_FACTURAS_TB
ORDER BY ID_FACTURA DESC;

COMMIT;
