CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_INSERT_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_REGISTRO IN TAREA1.FIDE_CLIENTES_TB.FECHA_REGISTRO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_CLIENTES_TB
(ID_CLIENTE,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_REGISTRO,ID_CORREO,ID_DIRECCION,ID_ESTADO)
VALUES
(P_ID_CLIENTE,P_NOMBRE,P_APELLIDO_PATERNO,P_APELLIDO_MATERNO,P_FECHA_REGISTRO,P_ID_CORREO,P_ID_DIRECCION,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_UPDATE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CLIENTES_TB
SET NOMBRE=P_NOMBRE,
APELLIDO_PATERNO=P_APELLIDO_PATERNO,
APELLIDO_MATERNO=P_APELLIDO_MATERNO,
ID_CORREO=P_ID_CORREO,
ID_DIRECCION=P_ID_DIRECCION
WHERE ID_CLIENTE=P_ID_CLIENTE;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_DELETE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CLIENTES_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_CLIENTE=P_ID_CLIENTE;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_MASCOTAS_INSERT_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_MASCOTAS_TB
(ID_MASCOTA,ID_CLIENTE,ID_RAZA,NOMBRE,EDAD,PESO,OBSERVACIONES,ID_ESTADO)
VALUES
(P_ID_MASCOTA,P_ID_CLIENTE,P_ID_RAZA,P_NOMBRE,P_EDAD,P_PESO,P_OBSERVACIONES,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_MASCOTAS_UPDATE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_MASCOTAS_TB
SET ID_CLIENTE=P_ID_CLIENTE,
ID_RAZA=P_ID_RAZA,
NOMBRE=P_NOMBRE,
EDAD=P_EDAD,
PESO=P_PESO,
OBSERVACIONES=P_OBSERVACIONES
WHERE ID_MASCOTA=P_ID_MASCOTA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_MASCOTAS_DELETE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_MASCOTAS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_MASCOTA=P_ID_MASCOTA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CITAS_INSERT_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_CITAS_TB
(ID_CITA,ID_MASCOTA,FECHA_HORA,NOTAS_GROOMER,ID_ESTADO)
VALUES
(P_ID_CITA,P_ID_MASCOTA,P_FECHA_HORA,P_NOTAS_GROOMER,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CITAS_UPDATE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CITAS_TB
SET ID_MASCOTA=P_ID_MASCOTA,
FECHA_HORA=P_FECHA_HORA,
NOTAS_GROOMER=P_NOTAS_GROOMER
WHERE ID_CITA=P_ID_CITA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CITAS_DELETE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CITAS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_CITA=P_ID_CITA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_INSERT_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_SERVICIOS_TB
(ID_SERVICIO,NOMBRE,DESCRIPCION,PRECIO_ESTANDAR,DURACION,ID_ESTADO)
VALUES
(P_ID_SERVICIO,P_NOMBRE,P_DESCRIPCION,P_PRECIO_ESTANDAR,P_DURACION,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_UPDATE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_SERVICIOS_TB
SET NOMBRE=P_NOMBRE,
DESCRIPCION=P_DESCRIPCION,
PRECIO_ESTANDAR=P_PRECIO_ESTANDAR,
DURACION=P_DURACION
WHERE ID_SERVICIO=P_ID_SERVICIO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_DELETE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_SERVICIOS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_SERVICIO=P_ID_SERVICIO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PAGOS_INSERT_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_CITA IN TAREA1.FIDE_PAGOS_TB.ID_CITA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_PAGOS_TB.ID_CLIENTE%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_PAGOS_TB
(ID_PAGO,ID_CITA,ID_CLIENTE,FECHA_PAGO,MONTO_TOTAL,METODO_PAGO,ID_ESTADO)
VALUES
(P_ID_PAGO,P_ID_CITA,P_ID_CLIENTE,P_FECHA_PAGO,P_MONTO_TOTAL,P_METODO_PAGO,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PAGOS_UPDATE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PAGOS_TB
SET FECHA_PAGO=P_FECHA_PAGO,
MONTO_TOTAL=P_MONTO_TOTAL,
METODO_PAGO=P_METODO_PAGO
WHERE ID_PAGO=P_ID_PAGO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PAGOS_DELETE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PAGOS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_PAGO=P_ID_PAGO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_INSERT_SP(
P_ID_PRODUCTO IN TAREA1.FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN TAREA1.FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
P_PRECIO_UNITARIO IN TAREA1.FIDE_PRODUCTOS_TB.PRECIO_UNITARIO%TYPE,
P_STOCK IN TAREA1.FIDE_PRODUCTOS_TB.STOCK%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PRODUCTOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_PRODUCTOS_TB
(ID_PRODUCTO,NOMBRE,DESCRIPCION,PRECIO_UNITARIO,STOCK,ID_ESTADO)
VALUES
(P_ID_PRODUCTO,P_NOMBRE,P_DESCRIPCION,P_PRECIO_UNITARIO,P_STOCK,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_UPDATE_SP(
P_ID_PRODUCTO IN TAREA1.FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN TAREA1.FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
P_PRECIO_UNITARIO IN TAREA1.FIDE_PRODUCTOS_TB.PRECIO_UNITARIO%TYPE,
P_STOCK IN TAREA1.FIDE_PRODUCTOS_TB.STOCK%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PRODUCTOS_TB
SET NOMBRE=P_NOMBRE,
DESCRIPCION=P_DESCRIPCION,
PRECIO_UNITARIO=P_PRECIO_UNITARIO,
STOCK=P_STOCK
WHERE ID_PRODUCTO=P_ID_PRODUCTO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_DELETE_SP(
P_ID_PRODUCTO IN TAREA1.FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PRODUCTOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PRODUCTOS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_PRODUCTO=P_ID_PRODUCTO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_VENTAS_INSERT_SP(
P_ID_VENTA IN TAREA1.FIDE_VENTAS_TB.ID_VENTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_VENTAS_TB.ID_CLIENTE%TYPE,
P_FECHA_VENTA IN TAREA1.FIDE_VENTAS_TB.FECHA_VENTA%TYPE,
P_TOTAL_VENTA IN TAREA1.FIDE_VENTAS_TB.TOTAL_VENTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_VENTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_VENTAS_TB
(ID_VENTA,ID_CLIENTE,FECHA_VENTA,TOTAL_VENTA,ID_ESTADO)
VALUES
(P_ID_VENTA,P_ID_CLIENTE,P_FECHA_VENTA,P_TOTAL_VENTA,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_VENTAS_UPDATE_SP(
P_ID_VENTA IN TAREA1.FIDE_VENTAS_TB.ID_VENTA%TYPE,
P_FECHA_VENTA IN TAREA1.FIDE_VENTAS_TB.FECHA_VENTA%TYPE,
P_TOTAL_VENTA IN TAREA1.FIDE_VENTAS_TB.TOTAL_VENTA%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_VENTAS_TB
SET FECHA_VENTA=P_FECHA_VENTA,
TOTAL_VENTA=P_TOTAL_VENTA
WHERE ID_VENTA=P_ID_VENTA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_VENTAS_DELETE_SP(
P_ID_VENTA IN TAREA1.FIDE_VENTAS_TB.ID_VENTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_VENTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_VENTAS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_VENTA=P_ID_VENTA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_INSERT_SP(
P_ID_FACTURA IN TAREA1.FIDE_FACTURAS_TB.ID_FACTURA%TYPE,
P_ID_VENTA IN TAREA1.FIDE_FACTURAS_TB.ID_VENTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_FACTURAS_TB.ID_CLIENTE%TYPE,
P_FECHA_EMISION IN TAREA1.FIDE_FACTURAS_TB.FECHA_EMISION%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_FACTURAS_TB.MONTO_TOTAL%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_FACTURAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_FACTURAS_TB
(ID_FACTURA,ID_VENTA,ID_CLIENTE,FECHA_EMISION,MONTO_TOTAL,ID_ESTADO)
VALUES
(P_ID_FACTURA,P_ID_VENTA,P_ID_CLIENTE,P_FECHA_EMISION,P_MONTO_TOTAL,P_ID_ESTADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_UPDATE_SP(
P_ID_FACTURA IN TAREA1.FIDE_FACTURAS_TB.ID_FACTURA%TYPE,
P_FECHA_EMISION IN TAREA1.FIDE_FACTURAS_TB.FECHA_EMISION%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_FACTURAS_TB.MONTO_TOTAL%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_FACTURAS_TB
SET FECHA_EMISION=P_FECHA_EMISION,
MONTO_TOTAL=P_MONTO_TOTAL
WHERE ID_FACTURA=P_ID_FACTURA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_DELETE_SP(
P_ID_FACTURA IN TAREA1.FIDE_FACTURAS_TB.ID_FACTURA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_FACTURAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_FACTURAS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_FACTURA=P_ID_FACTURA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_TELEFONOS_INSERT_SP(
P_ID_TELEFONO IN TAREA1.FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_TELEFONOS_TB.ID_CLIENTE%TYPE,
P_NUMERO_TELEFONO IN TAREA1.FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_TELEFONOS_TB (ID_TELEFONO,ID_CLIENTE,NUMERO_TELEFONO)
VALUES (P_ID_TELEFONO,P_ID_CLIENTE,P_NUMERO_TELEFONO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_TELEFONOS_UPDATE_SP(
P_ID_TELEFONO IN TAREA1.FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE,
P_NUMERO_TELEFONO IN TAREA1.FIDE_TELEFONOS_TB.NUMERO_TELEFONO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_TELEFONOS_TB
SET NUMERO_TELEFONO=P_NUMERO_TELEFONO
WHERE ID_TELEFONO=P_ID_TELEFONO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_TELEFONOS_DELETE_SP(
P_ID_TELEFONO IN TAREA1.FIDE_TELEFONOS_TB.ID_TELEFONO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_TELEFONOS_TB
WHERE ID_TELEFONO=P_ID_TELEFONO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CORREOS_INSERT_SP(
P_ID_CORREO IN TAREA1.FIDE_CORREOS_TB.ID_CORREO%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_CORREOS_TB.ID_CLIENTE%TYPE,
P_CORREO_ELECTRONICO IN TAREA1.FIDE_CORREOS_TB.CORREO_ELECTRONICO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_CORREOS_TB (ID_CORREO,ID_CLIENTE,CORREO_ELECTRONICO)
VALUES (P_ID_CORREO,P_ID_CLIENTE,P_CORREO_ELECTRONICO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CORREOS_UPDATE_SP(
P_ID_CORREO IN TAREA1.FIDE_CORREOS_TB.ID_CORREO%TYPE,
P_CORREO_ELECTRONICO IN TAREA1.FIDE_CORREOS_TB.CORREO_ELECTRONICO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_CORREOS_TB
SET CORREO_ELECTRONICO=P_CORREO_ELECTRONICO
WHERE ID_CORREO=P_ID_CORREO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_CORREOS_DELETE_SP(
P_ID_CORREO IN TAREA1.FIDE_CORREOS_TB.ID_CORREO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_CORREOS_TB
WHERE ID_CORREO=P_ID_CORREO;
COMMIT;
END;


CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_INSERT_SP(
P_ID_PROVINCIA IN TAREA1.FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN TAREA1.FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_PROVINCIAS_TB (ID_PROVINCIA,NOMBRE_PROVINCIA)
VALUES (P_ID_PROVINCIA,P_NOMBRE_PROVINCIA);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_UPDATE_SP(
P_ID_PROVINCIA IN TAREA1.FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN TAREA1.FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_PROVINCIAS_TB
SET NOMBRE_PROVINCIA=P_NOMBRE_PROVINCIA
WHERE ID_PROVINCIA=P_ID_PROVINCIA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_DELETE_SP(
P_ID_PROVINCIA IN TAREA1.FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_PROVINCIAS_TB
WHERE ID_PROVINCIA=P_ID_PROVINCIA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_INSERT_SP(
P_ID_DISTRITO IN TAREA1.FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN TAREA1.FIDE_DISTRITOS_TB.ID_CANTON%TYPE,
P_NOMBRE_DISTRITO IN TAREA1.FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_DISTRITOS_TB (ID_DISTRITO,ID_CANTON,NOMBRE_DISTRITO)
VALUES (P_ID_DISTRITO,P_ID_CANTON,P_NOMBRE_DISTRITO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_UPDATE_SP(
P_ID_DISTRITO IN TAREA1.FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN TAREA1.FIDE_DISTRITOS_TB.ID_CANTON%TYPE,
P_NOMBRE_DISTRITO IN TAREA1.FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_DISTRITOS_TB
SET ID_CANTON=P_ID_CANTON,
NOMBRE_DISTRITO=P_NOMBRE_DISTRITO
WHERE ID_DISTRITO=P_ID_DISTRITO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_DELETE_SP(
P_ID_DISTRITO IN TAREA1.FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_DISTRITOS_TB
WHERE ID_DISTRITO=P_ID_DISTRITO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_INSERT_SP(
P_ID_DIRECCION IN TAREA1.FIDE_DIRECCIONES_TB.ID_DIRECCION%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_DIRECCIONES_TB.ID_CLIENTE%TYPE,
P_ID_DISTRITO IN TAREA1.FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
P_DETALLE_DIRECCION IN TAREA1.FIDE_DIRECCIONES_TB.DETALLE_DIRECCION%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_DIRECCIONES_TB (ID_DIRECCION,ID_CLIENTE,ID_DISTRITO,DETALLE_DIRECCION)
VALUES (P_ID_DIRECCION,P_ID_CLIENTE,P_ID_DISTRITO,P_DETALLE_DIRECCION);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_UPDATE_SP(
P_ID_DIRECCION IN TAREA1.FIDE_DIRECCIONES_TB.ID_DIRECCION%TYPE,
P_ID_DISTRITO IN TAREA1.FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
P_DETALLE_DIRECCION IN TAREA1.FIDE_DIRECCIONES_TB.DETALLE_DIRECCION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_DIRECCIONES_TB
SET ID_DISTRITO=P_ID_DISTRITO,
DETALLE_DIRECCION=P_DETALLE_DIRECCION
WHERE ID_DIRECCION=P_ID_DIRECCION;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_DELETE_SP(
P_ID_DIRECCION IN TAREA1.FIDE_DIRECCIONES_TB.ID_DIRECCION%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_DIRECCIONES_TB
WHERE ID_DIRECCION=P_ID_DIRECCION;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_RAZA_INSERT_SP(
P_ID_RAZA IN TAREA1.FIDE_RAZA_TB.ID_RAZA%TYPE,
P_NOMBRE_RAZA IN TAREA1.FIDE_RAZA_TB.NOMBRE_RAZA%TYPE,
P_TIPO_ESPECIE IN TAREA1.FIDE_RAZA_TB.TIPO_ESPECIE%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_RAZA_TB (ID_RAZA,NOMBRE_RAZA,TIPO_ESPECIE)
VALUES (P_ID_RAZA,P_NOMBRE_RAZA,P_TIPO_ESPECIE);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_RAZA_UPDATE_SP(
P_ID_RAZA IN TAREA1.FIDE_RAZA_TB.ID_RAZA%TYPE,
P_NOMBRE_RAZA IN TAREA1.FIDE_RAZA_TB.NOMBRE_RAZA%TYPE,
P_TIPO_ESPECIE IN TAREA1.FIDE_RAZA_TB.TIPO_ESPECIE%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_RAZA_TB
SET NOMBRE_RAZA=P_NOMBRE_RAZA,
TIPO_ESPECIE=P_TIPO_ESPECIE
WHERE ID_RAZA=P_ID_RAZA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_RAZA_DELETE_SP(
P_ID_RAZA IN TAREA1.FIDE_RAZA_TB.ID_RAZA%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_RAZA_TB
WHERE ID_RAZA=P_ID_RAZA;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_CITA_INSERT_SP(
P_ID_CITA IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_CITA%TYPE,
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_SERVICIO%TYPE,
P_PRECIO_APLICADO IN TAREA1.FIDE_SERVICIOS_CITA_TB.PRECIO_APLICADO%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_SERVICIOS_CITA_TB (ID_CITA,ID_SERVICIO,PRECIO_APLICADO)
VALUES (P_ID_CITA,P_ID_SERVICIO,P_PRECIO_APLICADO);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_CITA_UPDATE_SP(
P_ID_CITA IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_CITA%TYPE,
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_SERVICIO%TYPE,
P_PRECIO_APLICADO IN TAREA1.FIDE_SERVICIOS_CITA_TB.PRECIO_APLICADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_SERVICIOS_CITA_TB
SET PRECIO_APLICADO=P_PRECIO_APLICADO
WHERE ID_CITA=P_ID_CITA
AND ID_SERVICIO=P_ID_SERVICIO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_CITA_DELETE_SP(
P_ID_CITA IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_CITA%TYPE,
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_CITA_TB.ID_SERVICIO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_SERVICIOS_CITA_TB
WHERE ID_CITA=P_ID_CITA
AND ID_SERVICIO=P_ID_SERVICIO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DETALLE_VENTA_INSERT_SP(
P_ID_VENTA IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_VENTA%TYPE,
P_ID_PRODUCTO IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_PRODUCTO%TYPE,
P_CANTIDAD IN TAREA1.FIDE_DETALLE_VENTA_TB.CANTIDAD%TYPE,
P_PRECIO_VENTA IN TAREA1.FIDE_DETALLE_VENTA_TB.PRECIO_VENTA%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_DETALLE_VENTA_TB (ID_VENTA,ID_PRODUCTO,CANTIDAD,PRECIO_VENTA)
VALUES (P_ID_VENTA,P_ID_PRODUCTO,P_CANTIDAD,P_PRECIO_VENTA);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DETALLE_VENTA_UPDATE_SP(
P_ID_VENTA IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_VENTA%TYPE,
P_ID_PRODUCTO IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_PRODUCTO%TYPE,
P_CANTIDAD IN TAREA1.FIDE_DETALLE_VENTA_TB.CANTIDAD%TYPE,
P_PRECIO_VENTA IN TAREA1.FIDE_DETALLE_VENTA_TB.PRECIO_VENTA%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_DETALLE_VENTA_TB
SET CANTIDAD=P_CANTIDAD,
PRECIO_VENTA=P_PRECIO_VENTA
WHERE ID_VENTA=P_ID_VENTA
AND ID_PRODUCTO=P_ID_PRODUCTO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_DETALLE_VENTA_DELETE_SP(
P_ID_VENTA IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_VENTA%TYPE,
P_ID_PRODUCTO IN TAREA1.FIDE_DETALLE_VENTA_TB.ID_PRODUCTO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_DETALLE_VENTA_TB
WHERE ID_VENTA=P_ID_VENTA
AND ID_PRODUCTO=P_ID_PRODUCTO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_ESTADOS_INSERT_SP(
P_ID_ESTADO IN TAREA1.FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN TAREA1.FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_ESTADOS_TB.DESCRIPCION%TYPE
) IS
BEGIN
INSERT INTO TAREA1.FIDE_ESTADOS_TB (ID_ESTADO,NOMBRE_ESTADO,DESCRIPCION)
VALUES (P_ID_ESTADO,P_NOMBRE_ESTADO,P_DESCRIPCION);
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_ESTADOS_UPDATE_SP(
P_ID_ESTADO IN TAREA1.FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN TAREA1.FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_ESTADOS_TB.DESCRIPCION%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_ESTADOS_TB
SET NOMBRE_ESTADO=P_NOMBRE_ESTADO,
DESCRIPCION=P_DESCRIPCION
WHERE ID_ESTADO=P_ID_ESTADO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_ESTADOS_DELETE_SP(
P_ID_ESTADO IN TAREA1.FIDE_ESTADOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
DELETE FROM TAREA1.FIDE_ESTADOS_TB
WHERE ID_ESTADO=P_ID_ESTADO;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE FIDE_SERVICIOS_MAS_USADOS_X_ESPECIE_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('ESPECIE | SERVICIO | USOS');
FOR r IN (
SELECT
ra.TIPO_ESPECIE AS ESPECIE,
s.NOMBRE AS SERVICIO,
COUNT(*) AS USOS
FROM TAREA1.FIDE_SERVICIOS_CITA_TB sc
JOIN TAREA1.FIDE_SERVICIOS_TB s
ON s.ID_SERVICIO=sc.ID_SERVICIO
JOIN TAREA1.FIDE_CITAS_TB c
ON c.ID_CITA=sc.ID_CITA
JOIN TAREA1.FIDE_MASCOTAS_TB m
ON m.ID_MASCOTA=c.ID_MASCOTA
JOIN TAREA1.FIDE_RAZA_TB ra
ON ra.ID_RAZA=m.ID_RAZA
GROUP BY ra.TIPO_ESPECIE,s.NOMBRE
ORDER BY ra.TIPO_ESPECIE,COUNT(*) DESC,s.NOMBRE
) LOOP
DBMS_OUTPUT.PUT_LINE(r.ESPECIE||' | '||r.SERVICIO||' | '||r.USOS);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_CON_MAS_DE_UNA_MASCOTA_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('ID_CLIENTE | NOMBRE_COMPLETO | CANT_MASCOTAS');
FOR r IN (
SELECT
c.ID_CLIENTE,
(c.NOMBRE||' '||c.APELLIDO_PATERNO||' '||c.APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
COUNT(m.ID_MASCOTA) AS CANT_MASCOTAS
FROM TAREA1.FIDE_CLIENTES_TB c
JOIN TAREA1.FIDE_MASCOTAS_TB m
ON m.ID_CLIENTE=c.ID_CLIENTE
GROUP BY c.ID_CLIENTE,c.NOMBRE,c.APELLIDO_PATERNO,c.APELLIDO_MATERNO
HAVING COUNT(m.ID_MASCOTA)>1
ORDER BY COUNT(m.ID_MASCOTA) DESC,c.ID_CLIENTE
) LOOP
DBMS_OUTPUT.PUT_LINE(r.ID_CLIENTE||' | '||r.NOMBRE_COMPLETO||' | '||r.CANT_MASCOTAS);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_MASCOTAS_X_CLIENTE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
) IS
BEGIN
DBMS_OUTPUT.PUT_LINE('MASCOTAS DEL CLIENTE: '||P_ID_CLIENTE);
DBMS_OUTPUT.PUT_LINE('ID_MASCOTA | NOMBRE | ESPECIE | RAZA | EDAD | PESO');
FOR r IN (
SELECT
m.ID_MASCOTA,
m.NOMBRE AS NOMBRE_MASCOTA,
ra.TIPO_ESPECIE,
ra.NOMBRE_RAZA,
m.EDAD,
m.PESO
FROM TAREA1.FIDE_MASCOTAS_TB m
JOIN TAREA1.FIDE_RAZA_TB ra
ON ra.ID_RAZA=m.ID_RAZA
WHERE m.ID_CLIENTE=P_ID_CLIENTE
ORDER BY m.ID_MASCOTA
) LOOP
DBMS_OUTPUT.PUT_LINE(
r.ID_MASCOTA||' | '||
r.NOMBRE_MASCOTA||' | '||
r.TIPO_ESPECIE||' | '||
r.NOMBRE_RAZA||' | '||
NVL(TO_CHAR(r.EDAD),'NULL')||' | '||
NVL(TO_CHAR(r.PESO),'NULL')
);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_NOMBRES_UNICOS_MASCOTAS_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('NOMBRES UNICOS DE MASCOTAS:');
FOR r IN (
SELECT DISTINCT NOMBRE
FROM TAREA1.FIDE_MASCOTAS_TB
WHERE NOMBRE IS NOT NULL
ORDER BY NOMBRE
) LOOP
DBMS_OUTPUT.PUT_LINE(r.NOMBRE);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_CITAS_CANCELADAS_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('CITAS CANCELADAS:');
DBMS_OUTPUT.PUT_LINE('ID_CITA | FECHA_HORA | MASCOTA | CLIENTE');
FOR r IN (
SELECT
c.ID_CITA,
c.FECHA_HORA,
m.NOMBRE AS NOMBRE_MASCOTA,
(cl.NOMBRE||' '||cl.APELLIDO_PATERNO||' '||cl.APELLIDO_MATERNO) AS NOMBRE_CLIENTE
FROM TAREA1.FIDE_CITAS_TB c
JOIN TAREA1.FIDE_MASCOTAS_TB m
ON m.ID_MASCOTA=c.ID_MASCOTA
JOIN TAREA1.FIDE_CLIENTES_TB cl
ON cl.ID_CLIENTE=m.ID_CLIENTE
JOIN TAREA1.FIDE_ESTADOS_TB e
ON e.ID_ESTADO=c.ID_ESTADO
WHERE UPPER(e.NOMBRE_ESTADO)='CANCELADO'
ORDER BY c.FECHA_HORA DESC
) LOOP
DBMS_OUTPUT.PUT_LINE(
r.ID_CITA||' | '||
TO_CHAR(r.FECHA_HORA,'YYYY-MM-DD HH24:MI')||' | '||
r.NOMBRE_MASCOTA||' | '||
r.NOMBRE_CLIENTE
);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_CITAS_PENDIENTES_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('CITAS PENDIENTES:');
DBMS_OUTPUT.PUT_LINE('ID_CITA | FECHA_HORA | MASCOTA | CLIENTE');
FOR r IN (
SELECT
c.ID_CITA,
c.FECHA_HORA,
m.NOMBRE AS NOMBRE_MASCOTA,
(cl.NOMBRE||' '||cl.APELLIDO_PATERNO||' '||cl.APELLIDO_MATERNO) AS NOMBRE_CLIENTE
FROM TAREA1.FIDE_CITAS_TB c
JOIN TAREA1.FIDE_MASCOTAS_TB m
ON m.ID_MASCOTA=c.ID_MASCOTA
JOIN TAREA1.FIDE_CLIENTES_TB cl
ON cl.ID_CLIENTE=m.ID_CLIENTE
JOIN TAREA1.FIDE_ESTADOS_TB e
ON e.ID_ESTADO=c.ID_ESTADO
WHERE UPPER(e.NOMBRE_ESTADO)='PENDIENTE'
ORDER BY c.FECHA_HORA ASC
) LOOP
DBMS_OUTPUT.PUT_LINE(
r.ID_CITA||' | '||
TO_CHAR(r.FECHA_HORA,'YYYY-MM-DD HH24:MI')||' | '||
r.NOMBRE_MASCOTA||' | '||
r.NOMBRE_CLIENTE
);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_NO_ACTIVOS_SP IS
BEGIN
DBMS_OUTPUT.PUT_LINE('PRODUCTOS NO ACTIVOS:');
DBMS_OUTPUT.PUT_LINE('ID_PRODUCTO | NOMBRE | ESTADO | STOCK | PRECIO');
FOR r IN (
SELECT
p.ID_PRODUCTO,
p.NOMBRE,
e.NOMBRE_ESTADO,
p.STOCK,
p.PRECIO_UNITARIO
FROM TAREA1.FIDE_PRODUCTOS_TB p
JOIN TAREA1.FIDE_ESTADOS_TB e
ON e.ID_ESTADO=p.ID_ESTADO
WHERE UPPER(e.NOMBRE_ESTADO)<>'ACTIVO'
ORDER BY p.ID_PRODUCTO
) LOOP
DBMS_OUTPUT.PUT_LINE(
r.ID_PRODUCTO||' | '||
r.NOMBRE||' | '||
r.NOMBRE_ESTADO||' | '||
r.STOCK||' | '||
r.PRECIO_UNITARIO
);
END LOOP;
END;

CREATE OR REPLACE PROCEDURE FIDE_CAMBIAR_ESTADO_MASCOTA_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
UPDATE TAREA1.FIDE_MASCOTAS_TB
SET ID_ESTADO=P_ID_ESTADO
WHERE ID_MASCOTA=P_ID_MASCOTA;
COMMIT;
END;


commit;















