CREATE OR REPLACE PACKAGE FIDE_TAREA3_PCK AS

PROCEDURE FIDE_CLIENTES_INSERT_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_REGISTRO IN TAREA1.FIDE_CLIENTES_TB.FECHA_REGISTRO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
);



PROCEDURE FIDE_CLIENTES_UPDATE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_NOMBRE IN TAREA1.FIDE_CLIENTES_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN TAREA1.FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
P_ID_CORREO IN TAREA1.FIDE_CLIENTES_TB.ID_CORREO%TYPE,
P_ID_DIRECCION IN TAREA1.FIDE_CLIENTES_TB.ID_DIRECCION%TYPE
);

PROCEDURE FIDE_CLIENTES_DELETE_SP(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CLIENTES_TB.ID_ESTADO%TYPE
);


PROCEDURE FIDE_MASCOTAS_INSERT_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_MASCOTAS_UPDATE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_MASCOTAS_TB.ID_CLIENTE%TYPE,
P_ID_RAZA IN TAREA1.FIDE_MASCOTAS_TB.ID_RAZA%TYPE,
P_NOMBRE IN TAREA1.FIDE_MASCOTAS_TB.NOMBRE%TYPE,
P_EDAD IN TAREA1.FIDE_MASCOTAS_TB.EDAD%TYPE,
P_PESO IN TAREA1.FIDE_MASCOTAS_TB.PESO%TYPE,
P_OBSERVACIONES IN TAREA1.FIDE_MASCOTAS_TB.OBSERVACIONES%TYPE
);

PROCEDURE FIDE_MASCOTAS_DELETE_SP(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_MASCOTAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CITAS_INSERT_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_CITAS_UPDATE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_MASCOTA IN TAREA1.FIDE_CITAS_TB.ID_MASCOTA%TYPE,
P_FECHA_HORA IN TAREA1.FIDE_CITAS_TB.FECHA_HORA%TYPE,
P_NOTAS_GROOMER IN TAREA1.FIDE_CITAS_TB.NOTAS_GROOMER%TYPE
);

PROCEDURE FIDE_CITAS_DELETE_SP(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_CITAS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_SERVICIOS_INSERT_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_SERVICIOS_UPDATE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN TAREA1.FIDE_SERVICIOS_TB.NOMBRE%TYPE,
P_DESCRIPCION IN TAREA1.FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
P_PRECIO_ESTANDAR IN TAREA1.FIDE_SERVICIOS_TB.PRECIO_ESTANDAR%TYPE,
P_DURACION IN TAREA1.FIDE_SERVICIOS_TB.DURACION%TYPE
);

PROCEDURE FIDE_SERVICIOS_DELETE_SP(
P_ID_SERVICIO IN TAREA1.FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PAGOS_INSERT_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_CITA IN TAREA1.FIDE_PAGOS_TB.ID_CITA%TYPE,
P_ID_CLIENTE IN TAREA1.FIDE_PAGOS_TB.ID_CLIENTE%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
);

PROCEDURE FIDE_PAGOS_UPDATE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_FECHA_PAGO IN TAREA1.FIDE_PAGOS_TB.FECHA_PAGO%TYPE,
P_MONTO_TOTAL IN TAREA1.FIDE_PAGOS_TB.MONTO_TOTAL%TYPE,
P_METODO_PAGO IN TAREA1.FIDE_PAGOS_TB.METODO_PAGO%TYPE
);

PROCEDURE FIDE_PAGOS_DELETE_SP(
P_ID_PAGO IN TAREA1.FIDE_PAGOS_TB.ID_PAGO%TYPE,
P_ID_ESTADO IN TAREA1.FIDE_PAGOS_TB.ID_ESTADO%TYPE
);

FUNCTION FIDE_FN_MASCOTAS_POR_CLIENTE(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
) RETURN NUMBER;

FUNCTION FIDE_FN_ULTIMA_CITA_MASCOTA(
P_ID_MASCOTA IN TAREA1.FIDE_MASCOTAS_TB.ID_MASCOTA%TYPE
) RETURN DATE;

FUNCTION FIDE_FN_ESTADO_FACTURA(
P_ID_FACTURA IN TAREA1.FIDE_FACTURAS_TB.ID_FACTURA%TYPE
) RETURN VARCHAR2;

FUNCTION FIDE_FN_TOTAL_SERVICIOS_CITA(
P_ID_CITA IN TAREA1.FIDE_CITAS_TB.ID_CITA%TYPE
) RETURN NUMBER;

FUNCTION FIDE_FN_TOTAL_PAGADO_CLIENTE(
P_ID_CLIENTE IN TAREA1.FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
) RETURN NUMBER;

FUNCTION FIDE_FN_SERVICIO_MAS_UTILIZADO
RETURN VARCHAR2;

END FIDE_TAREA3_PCK;
/