CREATE USER TAREA4 IDENTIFIED BY Password123456;
COMMIT;

GRANT CREATE SESSION TO TAREA4;
GRANT CREATE TABLE TO TAREA4;
GRANT CREATE VIEW TO TAREA4;
GRANT CREATE PROCEDURE TO TAREA4;
GRANT CREATE SEQUENCE TO TAREA4;
GRANT CREATE TRIGGER TO TAREA4;
GRANT UNLIMITED TABLESPACE TO TAREA4;
COMMIT;

GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_ESTADOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CLIENTES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_TELEFONOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CORREOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PROVINCIAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CANTONES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DISTRITOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DIRECCIONES_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_RAZA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_MASCOTAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_CITAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_SERVICIOS_CITA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PAGOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_PRODUCTOS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_VENTAS_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_DETALLE_VENTA_TB TO TAREA4;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREA1.FIDE_FACTURAS_TB TO TAREA4;
COMMIT;

ALTER TABLE TAREA1.FIDE_ESTADOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_CLIENTES_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_TELEFONOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_CORREOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);


ALTER TABLE TAREA1.FIDE_PROVINCIAS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);




ALTER TABLE TAREA1.FIDE_CANTONES_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_DISTRITOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_DIRECCIONES_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_RAZA_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_MASCOTAS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_CITAS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);



ALTER TABLE TAREA1.FIDE_SERVICIOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_SERVICIOS_CITA_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_PAGOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);



ALTER TABLE TAREA1.FIDE_PRODUCTOS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_VENTAS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_DETALLE_VENTA_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10)
);

ALTER TABLE TAREA1.FIDE_FACTURAS_TB ADD (
AUDIT_FECHA_CREACION DATE DEFAULT SYSDATE,
AUDIT_USUARIO_CREACION VARCHAR2(100) DEFAULT USER,
AUDIT_FECHA_MODIFICA DATE,
AUDIT_USUARIO_MODIFICA VARCHAR2(100),
AUDIT_ACCION VARCHAR2(10),
NUM_FACTURA VARCHAR2(30)
);

COMMIT;

--SELECT COLUMN_NAME, DATA_TYPE, NULLABLE-
--FROM ALL_TAB_COLUMNS-
--WHERE OWNER = 'TAREA1'-
--AND TABLE_NAME = 'FIDE_CLIENTES_TB'-
--AND COLUMN_NAME LIKE 'AUDIT%'-
--ORDER BY COLUMN_ID;-


CREATE SEQUENCE TAREA1.SEQ_FIDE_ESTADOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CLIENTES
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_TELEFONOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CORREOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PROVINCIAS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CANTONES
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_DISTRITOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_DIRECCIONES
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_RAZA
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_MASCOTAS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_CITAS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_SERVICIOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_SERVICIOS_CITA
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PAGOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_PRODUCTOS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_VENTAS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_FACTURAS
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAREA1.SEQ_FIDE_NUM_FACTURA
START WITH 1 INCREMENT BY 1 MAXVALUE 9999999 NOCACHE NOCYCLE;

COMMIT;

--SELECT SEQUENCE_NAME, MIN_VALUE, INCREMENT_BY, CYCLE_FLAG, LAST_NUMBER
--FROM ALL_SEQUENCES
--WHERE SEQUENCE_OWNER = 'TAREA1'
--ORDER BY SEQUENCE_NAME;

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_ESTADOS_ID
BEFORE INSERT ON TAREA1.FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_ESTADO IS NULL THEN
:NEW.ID_ESTADO := TAREA1.SEQ_FIDE_ESTADOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CLIENTES_ID
BEFORE INSERT ON TAREA1.FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_CLIENTE IS NULL THEN
:NEW.ID_CLIENTE := TAREA1.SEQ_FIDE_CLIENTES.NEXTVAL;
END IF;
END;


CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_TELEFONOS_ID
BEFORE INSERT ON TAREA1.FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_TELEFONO IS NULL THEN
:NEW.ID_TELEFONO := TAREA1.SEQ_FIDE_TELEFONOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CORREOS_ID
BEFORE INSERT ON TAREA1.FIDE_CORREOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_CORREO IS NULL THEN
:NEW.ID_CORREO := TAREA1.SEQ_FIDE_CORREOS.NEXTVAL;
END IF;
END;


CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PROVINCIAS_ID
BEFORE INSERT ON TAREA1.FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_PROVINCIA IS NULL THEN
:NEW.ID_PROVINCIA := TAREA1.SEQ_FIDE_PROVINCIAS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CANTONES_ID
BEFORE INSERT ON TAREA1.FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_CANTON IS NULL THEN
:NEW.ID_CANTON := TAREA1.SEQ_FIDE_CANTONES.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_DISTRITOS_ID
BEFORE INSERT ON TAREA1.FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_DISTRITO IS NULL THEN
:NEW.ID_DISTRITO := TAREA1.SEQ_FIDE_DISTRITOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_DIRECCIONES_ID
BEFORE INSERT ON TAREA1.FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_DIRECCION IS NULL THEN
:NEW.ID_DIRECCION := TAREA1.SEQ_FIDE_DIRECCIONES.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_RAZA_ID
BEFORE INSERT ON TAREA1.FIDE_RAZA_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_RAZA IS NULL THEN
:NEW.ID_RAZA := TAREA1.SEQ_FIDE_RAZA.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_MASCOTAS_ID
BEFORE INSERT ON TAREA1.FIDE_MASCOTAS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_MASCOTA IS NULL THEN
:NEW.ID_MASCOTA := TAREA1.SEQ_FIDE_MASCOTAS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_CITAS_ID
BEFORE INSERT ON TAREA1.FIDE_CITAS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_CITA IS NULL THEN
:NEW.ID_CITA := TAREA1.SEQ_FIDE_CITAS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_SERVICIOS_ID
BEFORE INSERT ON TAREA1.FIDE_SERVICIOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_SERVICIO IS NULL THEN
:NEW.ID_SERVICIO := TAREA1.SEQ_FIDE_SERVICIOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PAGOS_ID
BEFORE INSERT ON TAREA1.FIDE_PAGOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_PAGO IS NULL THEN
:NEW.ID_PAGO := TAREA1.SEQ_FIDE_PAGOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_PRODUCTOS_ID
BEFORE INSERT ON TAREA1.FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_PRODUCTO IS NULL THEN
:NEW.ID_PRODUCTO := TAREA1.SEQ_FIDE_PRODUCTOS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_VENTAS_ID
BEFORE INSERT ON TAREA1.FIDE_VENTAS_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_VENTA IS NULL THEN
:NEW.ID_VENTA := TAREA1.SEQ_FIDE_VENTAS.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_FACTURAS_ID
BEFORE INSERT ON TAREA1.FIDE_FACTURAS_TB
FOR EACH ROW
DECLARE
V_SEQ NUMBER;
BEGIN
IF :NEW.ID_FACTURA IS NULL THEN
:NEW.ID_FACTURA := TAREA1.SEQ_FIDE_FACTURAS.NEXTVAL;
END IF;
IF :NEW.NUM_FACTURA IS NULL THEN
V_SEQ := TAREA1.SEQ_FIDE_NUM_FACTURA.NEXTVAL;
:NEW.NUM_FACTURA := TO_CHAR(SYSDATE, 'YYYY') || '1811' || LPAD(TO_CHAR(V_SEQ), 7, '0') || '-A';
END IF;
END;
/

--SELECT TRIGGER_NAME, TRIGGER_TYPE, TRIGGERING_EVENT, TABLE_NAME, STATUS
--FROM ALL_TRIGGERS
--WHERE OWNER = 'TAREA1'
--AND TRIGGER_NAME LIKE 'TRG_FIDE_%_ID'
--ORDER BY TABLE_NAME;

commit;

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_ESTADOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_ESTADOS_TB | ID: ' || :OLD.ID_ESTADO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_CLIENTES
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_CLIENTES_TB | ID: ' || :OLD.ID_CLIENTE || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_TELEFONOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_TELEFONOS_TB | ID: ' || :OLD.ID_TELEFONO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_CORREOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CORREOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_CORREOS_TB | ID: ' || :OLD.ID_CORREO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_PROVINCIAS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_PROVINCIAS_TB | ID: ' || :OLD.ID_PROVINCIA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_CANTONES
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_CANTONES_TB | ID: ' || :OLD.ID_CANTON || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_DISTRITOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_DISTRITOS_TB | ID: ' || :OLD.ID_DISTRITO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_DIRECCIONES
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_DIRECCIONES_TB | ID: ' || :OLD.ID_DIRECCION || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_RAZA
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_RAZA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_RAZA_TB | ID: ' || :OLD.ID_RAZA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_MASCOTAS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_MASCOTAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_MASCOTAS_TB | ID: ' || :OLD.ID_MASCOTA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_CITAS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CITAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_CITAS_TB | ID: ' || :OLD.ID_CITA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_SERVICIOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_SERVICIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_SERVICIOS_TB | ID: ' || :OLD.ID_SERVICIO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_SERVICIOS_CITA
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_SERVICIOS_CITA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_SERVICIOS_CITA_TB | ID_CITA: ' || :OLD.ID_CITA || ' ID_SERVICIO: ' || :OLD.ID_SERVICIO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_PAGOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_PAGOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_PAGOS_TB | ID: ' || :OLD.ID_PAGO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_PRODUCTOS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_PRODUCTOS_TB | ID: ' || :OLD.ID_PRODUCTO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_VENTAS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_VENTAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_VENTAS_TB | ID: ' || :OLD.ID_VENTA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_DETALLE_VENTA
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_DETALLE_VENTA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_DETALLE_VENTA_TB | ID_VENTA: ' || :OLD.ID_VENTA || ' ID_PRODUCTO: ' || :OLD.ID_PRODUCTO || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_AUDIT_FIDE_FACTURAS
BEFORE INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.AUDIT_FECHA_CREACION := SYSDATE;
:NEW.AUDIT_USUARIO_CREACION := USER;
:NEW.AUDIT_ACCION := 'INSERT';
ELSIF UPDATING THEN
:NEW.AUDIT_FECHA_MODIFICA := SYSDATE;
:NEW.AUDIT_USUARIO_MODIFICA := USER;
:NEW.AUDIT_ACCION := 'UPDATE';
ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('DELETE en FIDE_FACTURAS_TB | ID: ' || :OLD.ID_FACTURA || ' NUM_FACTURA: ' || :OLD.NUM_FACTURA || ' | Usuario: ' || USER || ' | Fecha: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
END IF;
END;
/

/*SELECT TRIGGER_NAME, TRIGGERING_EVENT, TABLE_NAME, STATUS
FROM ALL_TRIGGERS
WHERE OWNER = 'TAREA1'
AND TRIGGER_NAME LIKE 'TRG_AUDIT_%'
ORDER BY TABLE_NAME;*/


commit;

CREATE TABLE TAREA1.FIDE_AUDITORIA_TB (
ID_AUDITORIA NUMBER PRIMARY KEY,
TABLA_AFECTADA VARCHAR2(60) NOT NULL,
ACCION VARCHAR2(10) NOT NULL,
ID_REGISTRO VARCHAR2(200),
USUARIO_BD VARCHAR2(100) NOT NULL,
FECHA_HORA DATE NOT NULL,
DATOS_ANTERIORES VARCHAR2(4000),
DATOS_NUEVOS VARCHAR2(4000)
);

CREATE SEQUENCE TAREA1.SEQ_FIDE_AUDITORIA
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TAREA1.TRG_FIDE_AUDITORIA_ID
BEFORE INSERT ON TAREA1.FIDE_AUDITORIA_TB
FOR EACH ROW
BEGIN
IF :NEW.ID_AUDITORIA IS NULL THEN
:NEW.ID_AUDITORIA := TAREA1.SEQ_FIDE_AUDITORIA.NEXTVAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_ESTADOS
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_ESTADOS_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_ESTADO);
V_NEW_VAL := 'NOMBRE_ESTADO=' || :NEW.NOMBRE_ESTADO || ' | DESCRIPCION=' || :NEW.DESCRIPCION;
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_ESTADO);
V_OLD_VAL := 'NOMBRE_ESTADO=' || :OLD.NOMBRE_ESTADO || ' | DESCRIPCION=' || :OLD.DESCRIPCION;
V_NEW_VAL := 'NOMBRE_ESTADO=' || :NEW.NOMBRE_ESTADO || ' | DESCRIPCION=' || :NEW.DESCRIPCION;
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_ESTADO);
V_OLD_VAL := 'NOMBRE_ESTADO=' || :OLD.NOMBRE_ESTADO || ' | DESCRIPCION=' || :OLD.DESCRIPCION;
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_ESTADOS_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_CLIENTES
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CLIENTES_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_CLIENTE);
V_NEW_VAL := 'NOMBRE=' || :NEW.NOMBRE || ' | AP=' || :NEW.APELLIDO_PATERNO || ' | AM=' || :NEW.APELLIDO_MATERNO;
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_CLIENTE);
V_OLD_VAL := 'NOMBRE=' || :OLD.NOMBRE || ' | AP=' || :OLD.APELLIDO_PATERNO || ' | AM=' || :OLD.APELLIDO_MATERNO;
V_NEW_VAL := 'NOMBRE=' || :NEW.NOMBRE || ' | AP=' || :NEW.APELLIDO_PATERNO || ' | AM=' || :NEW.APELLIDO_MATERNO;
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_CLIENTE);
V_OLD_VAL := 'NOMBRE=' || :OLD.NOMBRE || ' | AP=' || :OLD.APELLIDO_PATERNO || ' | AM=' || :OLD.APELLIDO_MATERNO;
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_CLIENTES_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_MASCOTAS
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_MASCOTAS_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_MASCOTA);
V_NEW_VAL := 'NOMBRE=' || :NEW.NOMBRE || ' | ID_CLIENTE=' || :NEW.ID_CLIENTE || ' | ID_RAZA=' || :NEW.ID_RAZA;
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_MASCOTA);
V_OLD_VAL := 'NOMBRE=' || :OLD.NOMBRE || ' | ID_CLIENTE=' || :OLD.ID_CLIENTE || ' | ID_RAZA=' || :OLD.ID_RAZA;
V_NEW_VAL := 'NOMBRE=' || :NEW.NOMBRE || ' | ID_CLIENTE=' || :NEW.ID_CLIENTE || ' | ID_RAZA=' || :NEW.ID_RAZA;
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_MASCOTA);
V_OLD_VAL := 'NOMBRE=' || :OLD.NOMBRE || ' | ID_CLIENTE=' || :OLD.ID_CLIENTE || ' | ID_RAZA=' || :OLD.ID_RAZA;
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_MASCOTAS_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_CITAS
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_CITAS_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_CITA);
V_NEW_VAL := 'ID_MASCOTA=' || :NEW.ID_MASCOTA || ' | FECHA_HORA=' || TO_CHAR(:NEW.FECHA_HORA, 'DD/MM/YYYY HH24:MI');
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_CITA);
V_OLD_VAL := 'ID_MASCOTA=' || :OLD.ID_MASCOTA || ' | FECHA_HORA=' || TO_CHAR(:OLD.FECHA_HORA, 'DD/MM/YYYY HH24:MI');
V_NEW_VAL := 'ID_MASCOTA=' || :NEW.ID_MASCOTA || ' | FECHA_HORA=' || TO_CHAR(:NEW.FECHA_HORA, 'DD/MM/YYYY HH24:MI');
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_CITA);
V_OLD_VAL := 'ID_MASCOTA=' || :OLD.ID_MASCOTA || ' | FECHA_HORA=' || TO_CHAR(:OLD.FECHA_HORA, 'DD/MM/YYYY HH24:MI');
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_CITAS_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_PAGOS
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_PAGOS_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_PAGO);
V_NEW_VAL := 'ID_CLIENTE=' || :NEW.ID_CLIENTE || ' | MONTO=' || :NEW.MONTO_TOTAL || ' | METODO=' || :NEW.METODO_PAGO;
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_PAGO);
V_OLD_VAL := 'ID_CLIENTE=' || :OLD.ID_CLIENTE || ' | MONTO=' || :OLD.MONTO_TOTAL || ' | METODO=' || :OLD.METODO_PAGO;
V_NEW_VAL := 'ID_CLIENTE=' || :NEW.ID_CLIENTE || ' | MONTO=' || :NEW.MONTO_TOTAL || ' | METODO=' || :NEW.METODO_PAGO;
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_PAGO);
V_OLD_VAL := 'ID_CLIENTE=' || :OLD.ID_CLIENTE || ' | MONTO=' || :OLD.MONTO_TOTAL || ' | METODO=' || :OLD.METODO_PAGO;
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_PAGOS_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

CREATE OR REPLACE TRIGGER TAREA1.TRG_BITACORA_FIDE_FACTURAS
AFTER INSERT OR UPDATE OR DELETE ON TAREA1.FIDE_FACTURAS_TB
FOR EACH ROW
DECLARE
V_ACCION VARCHAR2(10);
V_PK VARCHAR2(200);
V_OLD_VAL VARCHAR2(4000);
V_NEW_VAL VARCHAR2(4000);
BEGIN
IF INSERTING THEN
V_ACCION := 'INSERT';
V_PK := TO_CHAR(:NEW.ID_FACTURA);
V_NEW_VAL := 'NUM_FACTURA=' || :NEW.NUM_FACTURA || ' | ID_VENTA=' || :NEW.ID_VENTA || ' | ID_CLIENTE=' || :NEW.ID_CLIENTE || ' | MONTO=' || :NEW.MONTO_TOTAL;
ELSIF UPDATING THEN
V_ACCION := 'UPDATE';
V_PK := TO_CHAR(:OLD.ID_FACTURA);
V_OLD_VAL := 'NUM_FACTURA=' || :OLD.NUM_FACTURA || ' | MONTO=' || :OLD.MONTO_TOTAL;
V_NEW_VAL := 'NUM_FACTURA=' || :NEW.NUM_FACTURA || ' | MONTO=' || :NEW.MONTO_TOTAL;
ELSIF DELETING THEN
V_ACCION := 'DELETE';
V_PK := TO_CHAR(:OLD.ID_FACTURA);
V_OLD_VAL := 'NUM_FACTURA=' || :OLD.NUM_FACTURA || ' | ID_VENTA=' || :OLD.ID_VENTA || ' | ID_CLIENTE=' || :OLD.ID_CLIENTE || ' | MONTO=' || :OLD.MONTO_TOTAL;
END IF;
INSERT INTO TAREA1.FIDE_AUDITORIA_TB (TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS)
VALUES ('FIDE_FACTURAS_TB', V_ACCION, V_PK, USER, SYSDATE, V_OLD_VAL, V_NEW_VAL);
END;
/

COMMIT;

/*SELECT TRIGGER_NAME, TRIGGERING_EVENT, TABLE_NAME, STATUS
FROM ALL_TRIGGERS
WHERE OWNER = 'TAREA1'
AND TRIGGER_NAME LIKE 'TRG_BITACORA_%'
ORDER BY TABLE_NAME;*/

SET SERVEROUTPUT ON;

-- triggers activos
SELECT TRIGGER_NAME, TRIGGERING_EVENT, TABLE_NAME, STATUS
FROM ALL_TRIGGERS
WHERE OWNER = 'TAREA1'
ORDER BY TABLE_NAME, TRIGGER_NAME;

--  secuencias creadas
SELECT SEQUENCE_NAME, MIN_VALUE, INCREMENT_BY, CYCLE_FLAG, LAST_NUMBER
FROM ALL_SEQUENCES
WHERE SEQUENCE_OWNER = 'TAREA1'
ORDER BY SEQUENCE_NAME;

-- Verificar columnas de auditoria FIDE_CLIENTES
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'TAREA1'
AND TABLE_NAME = 'FIDE_CLIENTES_TB'
AND COLUMN_NAME LIKE 'AUDIT%'
ORDER BY COLUMN_ID;

-- Prueba INSERT en FIDE_ESTADOS_TB

INSERT INTO TAREA1.FIDE_ESTADOS_TB (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('ACTIVO', 'Registro activo en el sistema');

INSERT INTO TAREA1.FIDE_ESTADOS_TB (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('INACTIVO', 'Registro inactivo');

COMMIT;

-- Verificar
SELECT ID_ESTADO, NOMBRE_ESTADO, AUDIT_FECHA_CREACION, AUDIT_USUARIO_CREACION, AUDIT_ACCION
FROM TAREA1.FIDE_ESTADOS_TB;

-- Prueba UPDATE
UPDATE TAREA1.FIDE_ESTADOS_TB
SET DESCRIPCION = 'Registro activo y disponible'
WHERE NOMBRE_ESTADO = 'ACTIVO';

COMMIT;

-- Verificar la auditoria
SELECT ID_ESTADO, NOMBRE_ESTADO, AUDIT_FECHA_MODIFICA, AUDIT_USUARIO_MODIFICA, AUDIT_ACCION
FROM TAREA1.FIDE_ESTADOS_TB;

COMMIT;






-- Prueba INSERT en FIDE_FACTURAS_TB

INSERT INTO TAREA1.FIDE_FACTURAS_TB (ID_VENTA, ID_CLIENTE, FECHA_EMISION, MONTO_TOTAL, ID_ESTADO)
VALUES (1, 1, SYSDATE, 25000, 1);
COMMIT;

-- numero alfanumerico generado
SELECT ID_FACTURA, NUM_FACTURA, AUDIT_FECHA_CREACION, AUDIT_USUARIO_CREACION
FROM TAREA1.FIDE_FACTURAS_TB;

-- Consultar la bitacora de auditoria historica
SELECT ID_AUDITORIA, TABLA_AFECTADA, ACCION, ID_REGISTRO, USUARIO_BD, FECHA_HORA, DATOS_ANTERIORES, DATOS_NUEVOS
FROM TAREA1.FIDE_AUDITORIA_TB
ORDER BY FECHA_HORA DESC;



