SELECT OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'FIDE_TAREA3_PCK';

SET SERVEROUTPUT ON;

BEGIN
DBMS_OUTPUT.PUT_LINE('Mascotas cliente 1: ' || FIDE_TAREA3_PCK.FIDE_FN_MASCOTAS_POR_CLIENTE(1));
DBMS_OUTPUT.PUT_LINE('Ultima cita mascota 1: ' || TO_CHAR(FIDE_TAREA3_PCK.FIDE_FN_ULTIMA_CITA_MASCOTA(1), 'DD/MM/YYYY HH24:MI'));
DBMS_OUTPUT.PUT_LINE('Estado factura 1: ' || FIDE_TAREA3_PCK.FIDE_FN_ESTADO_FACTURA(1));
DBMS_OUTPUT.PUT_LINE('Total servicios cita 1: ' || FIDE_TAREA3_PCK.FIDE_FN_TOTAL_SERVICIOS_CITA(1));
DBMS_OUTPUT.PUT_LINE('Total pagado cliente 1: ' || FIDE_TAREA3_PCK.FIDE_FN_TOTAL_PAGADO_CLIENTE(1));
DBMS_OUTPUT.PUT_LINE('Servicio más utilizado: ' || FIDE_TAREA3_PCK.FIDE_FN_SERVICIO_MAS_UTILIZADO);
END;
/
COMMIT;



