CREATE TABLE FIDE_ESTADOS_TB (
ID_ESTADO NUMBER PRIMARY KEY,
NOMBRE_ESTADO VARCHAR2(50),
DESCRIPCION VARCHAR2(100)
);

CREATE TABLE FIDE_CLIENTES_TB (
ID_CLIENTE NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100),
APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
APELLIDO_MATERNO VARCHAR2(100) NOT NULL,
FECHA_REGISTRO DATE NOT NULL,
ID_CORREO NUMBER NOT NULL,
ID_DIRECCION NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FK_FIDE_CLIENTES_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO) 
);

CREATE TABLE FIDE_TELEFONOS_TB (
ID_TELEFONO NUMBER PRIMARY KEY,
ID_CLIENTE NUMBER NOT NULL,
NUMERO_TELEFONO NUMBER(20),
CONSTRAINT FK_FIDE_NUMERO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE)
);

CREATE TABLE FIDE_CORREOS_TB (
ID_CORREO NUMBER PRIMARY KEY,
ID_CLIENTE NUMBER NOT NULL,
CORREO_ELECTRONICO VARCHAR2(150) NOT NULL,
CONSTRAINT FK_CORREO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE)
);


CREATE TABLE FIDE_PROVINCIAS_TB (
ID_PROVINCIA NUMBER PRIMARY KEY,
NOMBRE_PROVINCIA VARCHAR2(100)
);

CREATE TABLE FIDE_CANTONES_TB (
ID_CANTON NUMBER PRIMARY KEY,
ID_PROVINCIA NUMBER,
NOMBRE_CANTON VARCHAR2(100),
CONSTRAINT FK_FIDE_CANTONES_PROVINCIAS FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA)
);

CREATE TABLE FIDE_DISTRITOS_TB (
ID_DISTRITO NUMBER PRIMARY KEY,
ID_CANTON NUMBER,
NOMBRE_DISTRITO VARCHAR2(100),
CONSTRAINT FK_FIDE_DISTRITOS_CANTONES FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTONES_TB(ID_CANTON)
);

CREATE TABLE FIDE_DIRECCIONES_TB (
ID_DIRECCION NUMBER PRIMARY KEY,
ID_CLIENTE NUMBER,
ID_DISTRITO NUMBER,
DETALLE_DIRECCION VARCHAR2(250),
CONSTRAINT FK_FIDE_DIRECCION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
CONSTRAINT FK_FIDE_DIRECCION_DISTRITOS FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO)
);

CREATE TABLE FIDE_RAZA_TB (
ID_RAZA NUMBER PRIMARY KEY,
NOMBRE_RAZA VARCHAR2(100),
TIPO_ESPECIE VARCHAR2(50)
);

CREATE TABLE FIDE_MASCOTAS_TB (
ID_MASCOTA NUMBER PRIMARY KEY,
ID_CLIENTE NUMBER,
ID_RAZA NUMBER,
NOMBRE VARCHAR2(100),
EDAD NUMBER(3),
PESO NUMBER(5,2),
OBSERVACIONES VARCHAR2(300),
ID_ESTADO NUMBER,
CONSTRAINT FK_ESTADO_MASCOTA FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT FK_RAZA FOREIGN KEY (ID_RAZA) REFERENCES FIDE_RAZA_TB(ID_RAZA),
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE)
);

CREATE TABLE FIDE_CITAS_TB (
ID_CITA NUMBER PRIMARY KEY,
ID_MASCOTA NUMBER,
FECHA_HORA DATE,
NOTAS_GROOMER VARCHAR2(300),
ID_ESTADO NUMBER,
CONSTRAINT FK_ESTADO_CITAS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT FK_MASCOTA_CITAS FOREIGN KEY (ID_MASCOTA) REFERENCES FIDE_MASCOTAS_TB(ID_MASCOTA)
);

CREATE TABLE FIDE_SERVICIOS_TB (
ID_SERVICIO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(300),
PRECIO_ESTANDAR NUMBER(10,2),
DURACION NUMBER(4),
ID_ESTADO NUMBER,
CONSTRAINT FK_FIDE_ESTADO_SERVICIOS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_SERVICIOS_CITA_TB (
ID_CITA NUMBER PRIMARY KEY,
ID_SERVICIO NUMBER,
PRECIO_APLICADO NUMBER(10,2),
CONSTRAINT FK_SERVICIOS_CITA FOREIGN KEY (ID_SERVICIO) REFERENCES FIDE_SERVICIOS_TB(ID_SERVICIO)
);

CREATE TABLE FIDE_PAGOS_TB (
ID_PAGO NUMBER PRIMARY KEY,
ID_CITA NUMBER,
ID_CLIENTE NUMBER,
FECHA_PAGO DATE,
MONTO_TOTAL NUMBER(10,2),
METODO_PAGO VARCHAR2(50),
ID_ESTADO NUMBER,
CONSTRAINT FK_ESTADO_PAGO FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT FK_PAGO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
CONSTRAINT FK_CITA FOREIGN KEY (ID_CITA) REFERENCES FIDE_CITAS_TB
);

CREATE TABLE FIDE_PRODUCTOS_TB (
ID_PRODUCTO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(300),
PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
STOCK NUMBER(6) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FK_FIDE_PRODUCTOS_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_VENTAS_TB (
ID_VENTA NUMBER PRIMARY KEY,
ID_CLIENTE NUMBER NOT NULL,
FECHA_VENTA DATE NOT NULL,
TOTAL_VENTA NUMBER(10,2) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FK_FIDE_VENTAS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
CONSTRAINT FK_FIDE_VENTAS_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_DETALLE_VENTA_TB (
ID_VENTA NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
CANTIDAD NUMBER(5) NOT NULL,
PRECIO_VENTA NUMBER(10,2) NOT NULL,
CONSTRAINT PK_FIDE_DETALLE_VENTA_TB PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
CONSTRAINT FK_FIDE_DV_VENTAS FOREIGN KEY (ID_VENTA) REFERENCES FIDE_VENTAS_TB(ID_VENTA),
CONSTRAINT FK_FIDE_DV_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO)
);

CREATE TABLE FIDE_FACTURAS_TB (
ID_FACTURA NUMBER PRIMARY KEY,
ID_VENTA NUMBER NOT NULL,
ID_CLIENTE NUMBER NOT NULL,
FECHA_EMISION DATE NOT NULL,
MONTO_TOTAL NUMBER(10,2) NOT NULL,
ID_ESTADO NUMBER NOT NULL,
CONSTRAINT FK_FIDE_FACTURAS_VENTAS FOREIGN KEY (ID_VENTA) REFERENCES FIDE_VENTAS_TB(ID_VENTA),
CONSTRAINT FK_FIDE_FACTURAS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
CONSTRAINT FK_FIDE_FACTURAS_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

/* =========================================================
   PARCHE MÍNIMO para que tu script quede consistente y compile
   (Oracle SQL Developer)
   ========================================================= */

/* 1) Romper el ciclo: CLIENTES.ID_CORREO y CLIENTES.ID_DIRECCION NO pueden ser NOT NULL al inicio */
ALTER TABLE FIDE_CLIENTES_TB MODIFY (ID_CORREO NULL);
ALTER TABLE FIDE_CLIENTES_TB MODIFY (ID_DIRECCION NULL);

/* 2) Arreglar SERVICIOS_CITA: debe ser tabla puente con PK compuesta y FK a CITAS y SERVICIOS */
DROP TABLE FIDE_SERVICIOS_CITA_TB;

CREATE TABLE FIDE_SERVICIOS_CITA_TB (
  ID_CITA NUMBER NOT NULL,
  ID_SERVICIO NUMBER NOT NULL,
  PRECIO_APLICADO NUMBER(10,2),

  CONSTRAINT PK_FIDE_SERVICIOS_CITA_TB PRIMARY KEY (ID_CITA, ID_SERVICIO),

  CONSTRAINT FK_FIDE_SC_CITAS
    FOREIGN KEY (ID_CITA)
    REFERENCES FIDE_CITAS_TB(ID_CITA),

  CONSTRAINT FK_FIDE_SC_SERVICIOS
    FOREIGN KEY (ID_SERVICIO)
    REFERENCES FIDE_SERVICIOS_TB(ID_SERVICIO)
);

/* 3) Arreglar FK de PAGOS hacia CITAS (te faltó el campo referenciado) */
ALTER TABLE FIDE_PAGOS_TB DROP CONSTRAINT FK_CITA;

ALTER TABLE FIDE_PAGOS_TB
  ADD CONSTRAINT FK_CITA
  FOREIGN KEY (ID_CITA)
  REFERENCES FIDE_CITAS_TB(ID_CITA);

/* 4) Agregar las FK “principales” en CLIENTES hacia CORREOS y DIRECCIONES
      (se hacen DESPUÉS de existir esas tablas) */
ALTER TABLE FIDE_CLIENTES_TB
  ADD CONSTRAINT FK_FIDE_CLIENTES_CORREOS
  FOREIGN KEY (ID_CORREO)
  REFERENCES FIDE_CORREOS_TB(ID_CORREO);

ALTER TABLE FIDE_CLIENTES_TB
  ADD CONSTRAINT FK_FIDE_CLIENTES_DIRECCIONES
  FOREIGN KEY (ID_DIRECCION)
  REFERENCES FIDE_DIRECCIONES_TB(ID_DIRECCION);
